// Exercise library.
// Format: [name, primaryGroup, equipment, [secondaryGroups]]
// primaryGroup drives the calendar plate colors.

export const GROUPS = {
  chest:     { label: 'Chest',     color: '#D6252B', short: 'CH' },
  back:      { label: 'Back',      color: '#2E7FD9', short: 'BK' },
  legs:      { label: 'Legs',      color: '#F0BE1E', short: 'LG' },
  shoulders: { label: 'Shoulders', color: '#2AA85C', short: 'SH' },
  arms:      { label: 'Arms',      color: '#E8E5DE', short: 'AR' },
  core:      { label: 'Core',      color: '#A8AEB8', short: 'CO' }
};

export const GROUP_ORDER = ['chest', 'back', 'legs', 'shoulders', 'arms', 'core'];

const RAW = [
  // ---------- CHEST ----------
  ['Barbell Bench Press', 'chest', 'barbell', ['arms', 'shoulders']],
  ['Barbell Bench Press (Paused)', 'chest', 'barbell', ['arms', 'shoulders']],
  ['Close-Grip Bench Press', 'chest', 'barbell', ['arms']],
  ['Wide-Grip Bench Press', 'chest', 'barbell', ['shoulders']],
  ['Incline Barbell Bench Press', 'chest', 'barbell', ['shoulders', 'arms']],
  ['Decline Barbell Bench Press', 'chest', 'barbell', ['arms']],
  ['Floor Press', 'chest', 'barbell', ['arms']],
  ['Board Press', 'chest', 'barbell', ['arms']],
  ['Spoto Press', 'chest', 'barbell', ['arms']],
  ['Larsen Press', 'chest', 'barbell', ['arms']],
  ['Pin Press', 'chest', 'barbell', ['arms']],
  ['Dumbbell Bench Press', 'chest', 'dumbbell', ['arms', 'shoulders']],
  ['Incline Dumbbell Bench Press', 'chest', 'dumbbell', ['shoulders', 'arms']],
  ['Decline Dumbbell Bench Press', 'chest', 'dumbbell', ['arms']],
  ['Dumbbell Floor Press', 'chest', 'dumbbell', ['arms']],
  ['Dumbbell Flye', 'chest', 'dumbbell', []],
  ['Incline Dumbbell Flye', 'chest', 'dumbbell', []],
  ['Cable Flye (High to Low)', 'chest', 'cable', []],
  ['Cable Flye (Low to High)', 'chest', 'cable', []],
  ['Cable Flye (Mid)', 'chest', 'cable', []],
  ['Cable Crossover', 'chest', 'cable', []],
  ['Pec Deck', 'chest', 'machine', []],
  ['Machine Chest Press', 'chest', 'machine', ['arms']],
  ['Incline Machine Press', 'chest', 'machine', ['shoulders']],
  ['Smith Machine Bench Press', 'chest', 'machine', ['arms']],
  ['Push-Up', 'chest', 'bodyweight', ['arms', 'core']],
  ['Weighted Push-Up', 'chest', 'bodyweight', ['arms', 'core']],
  ['Deficit Push-Up', 'chest', 'bodyweight', ['arms']],
  ['Chest Dip', 'chest', 'bodyweight', ['arms']],
  ['Weighted Chest Dip', 'chest', 'bodyweight', ['arms']],
  ['Svend Press', 'chest', 'plate', []],
  ['Landmine Press', 'chest', 'barbell', ['shoulders']],

  // ---------- BACK ----------
  ['Conventional Deadlift', 'back', 'barbell', ['legs', 'core']],
  ['Sumo Deadlift', 'back', 'barbell', ['legs', 'core']],
  ['Deficit Deadlift', 'back', 'barbell', ['legs']],
  ['Block Pull', 'back', 'barbell', ['legs']],
  ['Rack Pull', 'back', 'barbell', ['legs']],
  ['Snatch-Grip Deadlift', 'back', 'barbell', ['legs']],
  ['Stiff-Leg Deadlift', 'back', 'barbell', ['legs']],
  ['Romanian Deadlift', 'back', 'barbell', ['legs']],
  ['Dumbbell Romanian Deadlift', 'back', 'dumbbell', ['legs']],
  ['Trap Bar Deadlift', 'back', 'barbell', ['legs']],
  ['Pull-Up', 'back', 'bodyweight', ['arms']],
  ['Weighted Pull-Up', 'back', 'bodyweight', ['arms']],
  ['Chin-Up', 'back', 'bodyweight', ['arms']],
  ['Weighted Chin-Up', 'back', 'bodyweight', ['arms']],
  ['Neutral-Grip Pull-Up', 'back', 'bodyweight', ['arms']],
  ['Assisted Pull-Up', 'back', 'machine', ['arms']],
  ['Lat Pulldown', 'back', 'cable', ['arms']],
  ['Close-Grip Lat Pulldown', 'back', 'cable', ['arms']],
  ['Neutral-Grip Lat Pulldown', 'back', 'cable', ['arms']],
  ['Reverse-Grip Lat Pulldown', 'back', 'cable', ['arms']],
  ['Single-Arm Lat Pulldown', 'back', 'cable', ['arms']],
  ['Straight-Arm Pulldown', 'back', 'cable', []],
  ['Barbell Row', 'back', 'barbell', ['arms']],
  ['Pendlay Row', 'back', 'barbell', ['arms']],
  ['Yates Row', 'back', 'barbell', ['arms']],
  ['T-Bar Row', 'back', 'barbell', ['arms']],
  ['Chest-Supported Row', 'back', 'machine', ['arms']],
  ['Seal Row', 'back', 'barbell', ['arms']],
  ['Dumbbell Row', 'back', 'dumbbell', ['arms']],
  ['Chest-Supported Dumbbell Row', 'back', 'dumbbell', ['arms']],
  ['Seated Cable Row', 'back', 'cable', ['arms']],
  ['Wide-Grip Seated Cable Row', 'back', 'cable', ['arms']],
  ['Single-Arm Cable Row', 'back', 'cable', ['arms']],
  ['Machine Row', 'back', 'machine', ['arms']],
  ['Meadows Row', 'back', 'barbell', ['arms']],
  ['Landmine Row', 'back', 'barbell', ['arms']],
  ['Inverted Row', 'back', 'bodyweight', ['arms']],
  ['Barbell Shrug', 'back', 'barbell', []],
  ['Dumbbell Shrug', 'back', 'dumbbell', []],
  ['Trap Bar Shrug', 'back', 'barbell', []],
  ['Cable Shrug', 'back', 'cable', []],
  ['Back Extension', 'back', 'bodyweight', ['legs']],
  ['Weighted Back Extension', 'back', 'bodyweight', ['legs']],
  ['Reverse Hyperextension', 'back', 'machine', ['legs']],
  ['Good Morning', 'back', 'barbell', ['legs']],
  ['Rope Face Pull', 'back', 'cable', ['shoulders']],
  ['Kroc Row', 'back', 'dumbbell', ['arms']],

  // ---------- LEGS ----------
  ['Back Squat (High Bar)', 'legs', 'barbell', ['core']],
  ['Back Squat (Low Bar)', 'legs', 'barbell', ['core', 'back']],
  ['Front Squat', 'legs', 'barbell', ['core']],
  ['Pause Squat', 'legs', 'barbell', ['core']],
  ['Box Squat', 'legs', 'barbell', ['core']],
  ['Safety Bar Squat', 'legs', 'barbell', ['core']],
  ['Zercher Squat', 'legs', 'barbell', ['core']],
  ['Overhead Squat', 'legs', 'barbell', ['shoulders', 'core']],
  ['Smith Machine Squat', 'legs', 'machine', []],
  ['Hack Squat', 'legs', 'machine', []],
  ['Pendulum Squat', 'legs', 'machine', []],
  ['Belt Squat', 'legs', 'machine', []],
  ['Goblet Squat', 'legs', 'dumbbell', ['core']],
  ['Bulgarian Split Squat', 'legs', 'dumbbell', ['core']],
  ['Barbell Split Squat', 'legs', 'barbell', ['core']],
  ['Walking Lunge', 'legs', 'dumbbell', ['core']],
  ['Reverse Lunge', 'legs', 'dumbbell', ['core']],
  ['Forward Lunge', 'legs', 'dumbbell', ['core']],
  ['Lateral Lunge', 'legs', 'dumbbell', []],
  ['Step-Up', 'legs', 'dumbbell', ['core']],
  ['Leg Press', 'legs', 'machine', []],
  ['Single-Leg Press', 'legs', 'machine', []],
  ['Leg Extension', 'legs', 'machine', []],
  ['Single-Leg Extension', 'legs', 'machine', []],
  ['Lying Leg Curl', 'legs', 'machine', []],
  ['Seated Leg Curl', 'legs', 'machine', []],
  ['Standing Leg Curl', 'legs', 'machine', []],
  ['Nordic Ham Curl', 'legs', 'bodyweight', []],
  ['Glute Ham Raise', 'legs', 'bodyweight', ['back']],
  ['Hip Thrust', 'legs', 'barbell', ['core']],
  ['Single-Leg Hip Thrust', 'legs', 'bodyweight', ['core']],
  ['Glute Bridge', 'legs', 'barbell', ['core']],
  ['Cable Pull-Through', 'legs', 'cable', ['back']],
  ['Cable Kickback', 'legs', 'cable', []],
  ['Hip Abduction Machine', 'legs', 'machine', []],
  ['Hip Adduction Machine', 'legs', 'machine', []],
  ['Standing Calf Raise', 'legs', 'machine', []],
  ['Seated Calf Raise', 'legs', 'machine', []],
  ['Leg Press Calf Raise', 'legs', 'machine', []],
  ['Smith Machine Calf Raise', 'legs', 'machine', []],
  ['Dumbbell Calf Raise', 'legs', 'dumbbell', []],
  ['Sissy Squat', 'legs', 'bodyweight', []],
  ['Sled Push', 'legs', 'machine', ['core']],
  ['Sled Drag', 'legs', 'machine', ['core']],
  ['Kettlebell Swing', 'legs', 'kettlebell', ['back', 'core']],

  // ---------- SHOULDERS ----------
  ['Overhead Press', 'shoulders', 'barbell', ['arms', 'core']],
  ['Push Press', 'shoulders', 'barbell', ['arms', 'legs']],
  ['Seated Barbell Overhead Press', 'shoulders', 'barbell', ['arms']],
  ['Behind-the-Neck Press', 'shoulders', 'barbell', ['arms']],
  ['Z Press', 'shoulders', 'barbell', ['core']],
  ['Dumbbell Shoulder Press', 'shoulders', 'dumbbell', ['arms']],
  ['Seated Dumbbell Shoulder Press', 'shoulders', 'dumbbell', ['arms']],
  ['Arnold Press', 'shoulders', 'dumbbell', ['arms']],
  ['Single-Arm Dumbbell Press', 'shoulders', 'dumbbell', ['core']],
  ['Machine Shoulder Press', 'shoulders', 'machine', ['arms']],
  ['Smith Machine Shoulder Press', 'shoulders', 'machine', ['arms']],
  ['Dumbbell Lateral Raise', 'shoulders', 'dumbbell', []],
  ['Cable Lateral Raise', 'shoulders', 'cable', []],
  ['Machine Lateral Raise', 'shoulders', 'machine', []],
  ['Leaning Lateral Raise', 'shoulders', 'dumbbell', []],
  ['Lu Raise', 'shoulders', 'dumbbell', []],
  ['Dumbbell Front Raise', 'shoulders', 'dumbbell', []],
  ['Plate Front Raise', 'shoulders', 'plate', []],
  ['Cable Front Raise', 'shoulders', 'cable', []],
  ['Dumbbell Rear Delt Flye', 'shoulders', 'dumbbell', ['back']],
  ['Cable Rear Delt Flye', 'shoulders', 'cable', ['back']],
  ['Reverse Pec Deck', 'shoulders', 'machine', ['back']],
  ['Upright Row', 'shoulders', 'barbell', ['back']],
  ['Cable Upright Row', 'shoulders', 'cable', ['back']],
  ['Barbell Cuban Press', 'shoulders', 'barbell', []],
  ['Band Pull-Apart', 'shoulders', 'band', ['back']],
  ['Handstand Push-Up', 'shoulders', 'bodyweight', ['arms']],
  ['Pike Push-Up', 'shoulders', 'bodyweight', ['arms']],

  // ---------- ARMS ----------
  ['Barbell Curl', 'arms', 'barbell', []],
  ['EZ-Bar Curl', 'arms', 'barbell', []],
  ['Wide-Grip Barbell Curl', 'arms', 'barbell', []],
  ['Close-Grip Barbell Curl', 'arms', 'barbell', []],
  ['Dumbbell Curl', 'arms', 'dumbbell', []],
  ['Alternating Dumbbell Curl', 'arms', 'dumbbell', []],
  ['Hammer Curl', 'arms', 'dumbbell', []],
  ['Cross-Body Hammer Curl', 'arms', 'dumbbell', []],
  ['Incline Dumbbell Curl', 'arms', 'dumbbell', []],
  ['Concentration Curl', 'arms', 'dumbbell', []],
  ['Preacher Curl', 'arms', 'barbell', []],
  ['Dumbbell Preacher Curl', 'arms', 'dumbbell', []],
  ['Machine Preacher Curl', 'arms', 'machine', []],
  ['Spider Curl', 'arms', 'dumbbell', []],
  ['Cable Curl', 'arms', 'cable', []],
  ['Rope Hammer Curl', 'arms', 'cable', []],
  ['Bayesian Cable Curl', 'arms', 'cable', []],
  ['Reverse Curl', 'arms', 'barbell', []],
  ['Zottman Curl', 'arms', 'dumbbell', []],
  ['21s', 'arms', 'barbell', []],
  ['Triceps Pushdown (Bar)', 'arms', 'cable', []],
  ['Triceps Pushdown (Rope)', 'arms', 'cable', []],
  ['Triceps Pushdown (V-Bar)', 'arms', 'cable', []],
  ['Reverse-Grip Pushdown', 'arms', 'cable', []],
  ['Overhead Cable Extension', 'arms', 'cable', []],
  ['Overhead Dumbbell Extension', 'arms', 'dumbbell', []],
  ['Single-Arm Overhead Extension', 'arms', 'dumbbell', []],
  ['Skullcrusher', 'arms', 'barbell', []],
  ['Dumbbell Skullcrusher', 'arms', 'dumbbell', []],
  ['JM Press', 'arms', 'barbell', ['chest']],
  ['Triceps Dip', 'arms', 'bodyweight', ['chest']],
  ['Bench Dip', 'arms', 'bodyweight', []],
  ['Diamond Push-Up', 'arms', 'bodyweight', ['chest']],
  ['Dumbbell Kickback', 'arms', 'dumbbell', []],
  ['Cable Kickback (Triceps)', 'arms', 'cable', []],
  ['Machine Triceps Extension', 'arms', 'machine', []],
  ['Wrist Curl', 'arms', 'barbell', []],
  ['Reverse Wrist Curl', 'arms', 'barbell', []],
  ['Behind-the-Back Wrist Curl', 'arms', 'barbell', []],
  ['Farmer\u2019s Walk', 'arms', 'dumbbell', ['core', 'back']],
  ['Plate Pinch Hold', 'arms', 'plate', []],
  ['Dead Hang', 'arms', 'bodyweight', ['back']],

  // ---------- CORE ----------
  ['Plank', 'core', 'bodyweight', []],
  ['Weighted Plank', 'core', 'bodyweight', []],
  ['Side Plank', 'core', 'bodyweight', []],
  ['RKC Plank', 'core', 'bodyweight', []],
  ['Ab Wheel Rollout', 'core', 'bodyweight', []],
  ['Barbell Rollout', 'core', 'barbell', []],
  ['Hanging Leg Raise', 'core', 'bodyweight', []],
  ['Hanging Knee Raise', 'core', 'bodyweight', []],
  ['Captain\u2019s Chair Leg Raise', 'core', 'bodyweight', []],
  ['Lying Leg Raise', 'core', 'bodyweight', []],
  ['Toes to Bar', 'core', 'bodyweight', []],
  ['Cable Crunch', 'core', 'cable', []],
  ['Machine Crunch', 'core', 'machine', []],
  ['Crunch', 'core', 'bodyweight', []],
  ['Weighted Crunch', 'core', 'plate', []],
  ['Sit-Up', 'core', 'bodyweight', []],
  ['Decline Sit-Up', 'core', 'bodyweight', []],
  ['Russian Twist', 'core', 'plate', []],
  ['Pallof Press', 'core', 'cable', []],
  ['Cable Woodchop', 'core', 'cable', []],
  ['Landmine Twist', 'core', 'barbell', []],
  ['Dead Bug', 'core', 'bodyweight', []],
  ['Bird Dog', 'core', 'bodyweight', ['back']],
  ['Hollow Body Hold', 'core', 'bodyweight', []],
  ['Suitcase Carry', 'core', 'dumbbell', ['arms']],
  ['Copenhagen Plank', 'core', 'bodyweight', ['legs']],
  ['Stir the Pot', 'core', 'bodyweight', []],
  ['Dragon Flag', 'core', 'bodyweight', []],

  // ---------- CARDIO / CONDITIONING ----------
  ['Treadmill Walk (Incline)', 'legs', 'cardio', []],
  ['Treadmill Run', 'legs', 'cardio', []],
  ['Stair Climber', 'legs', 'cardio', []],
  ['Stationary Bike', 'legs', 'cardio', []],
  ['Rowing Machine', 'back', 'cardio', ['legs']],
  ['Elliptical', 'legs', 'cardio', []],
  ['Assault Bike', 'legs', 'cardio', ['arms']],
  ['Jump Rope', 'legs', 'cardio', []],
  ['Outdoor Walk', 'legs', 'cardio', []]
];

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export const EXERCISES = RAW.map(([name, group, equipment, secondary]) => ({
  id: slug(name),
  name,
  group,
  equipment,
  secondary: secondary || [],
  custom: false
}));

export const EXERCISE_BY_ID = Object.fromEntries(EXERCISES.map(e => [e.id, e]));

export const EQUIPMENT = [
  'barbell', 'dumbbell', 'machine', 'cable', 'bodyweight',
  'kettlebell', 'band', 'plate', 'cardio'
];

export function makeCustomExercise(name, group, equipment) {
  return {
    id: 'custom-' + slug(name) + '-' + Math.random().toString(36).slice(2, 7),
    name: name.trim(),
    group,
    equipment: equipment || 'barbell',
    secondary: [],
    custom: true
  };
}
