export const meta = {
  name: 'v59-engine-3',
  description: 'V59 engine v3: the shared contract + engine asks of the deep two and the experimental specs (knob, greeting ink, tag type, stripes, hero numeral, chart·ink, lead-card hooks, new looks named), both trees, v1 byte-identical',
  phases: [{ title: 'Contract' }, { title: 'Engines' }, { title: 'Check' }],
}

// @@PREAMBLE@@

const NIGHT = '/Users/micahflunker/dev/vibes-night'
const WEB = `${NIGHT}/wt/web-ev3`
const NAT = `${NIGHT}/wt/nat-ev3`
const REF = `${NIGHT}/wt/web-mainref`
const HARNESS = `${NIGHT}/wt/web-harness/report/btn-44/prove.mjs`

const PLAN = `
MICAH'S CHANGE OF PLAN: you run at high effort; WIP branches run suites in UTC only (\`node ${NIGHT}/tools/run-verifiers.mjs <web|nat> <wt> <outDir> UTC\`); the orchestrator runs three zones at merge. No race hunts — anything new that is not a hard-rule failure goes under listed-not-fixed.
CURRENT MAINS (the session facts above are older): web main b99ec9d (engine v2 + Settings → Look → Vibes + the Chalk vibe), native main f3382d3 (the same). Other vibes are being built right now on their own branches (vibes/iron-age, vibes/navy, vibes/oxblood, both trees) — never touch those worktrees; you may READ their branches with git (\`git -C <repo> diff main...vibes/iron-age -- <path>\`) to reuse names they already chose for the same seam.
Commit WIP often (message via Write under ${NIGHT}/tmp/, \`git -C <wt> commit -F <file>\`, ending "Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>"; explicit paths only; never node_modules). A usage limit can end your session without warning. RESUMING: if git status / git log in the worktrees show earlier work for THIS job, an earlier agent died — review it and continue from it.`

const ASKS = `
===== ENGINE v3: THE SHARED ASKS OF THE DEEP AND EXPERIMENTAL SPECS =====
The three new specs: ${NIGHT}/design/{ledger,clear-sky,meet-day}.md, with pure definitions in ${NIGHT}/wt/web-design2/vibes/defs/{ledger,clear-sky,meet-day}.js and icon sets in ${NIGHT}/wt/web-design2/vibes/icons/<id>.js. Their collected engine asks and open items: ${NIGHT}/tmp/resume9/d4-specs.json (fields engine_asks, open). Read each spec's "Asks of the engine" section. Chalk (on main) asked some of the same in design/chalk.md; its AI judge flagged the accented greeting name.
Implement, ONCE and shared, every ask below that needs a shared file (the contract's pure files vibes/defs/{v1,index,vocab}.js + vibes/icons/v1.js; rack.css base rules/:root; auth.css; vibe.js; the web page modules only where a hook needs a class or attribute; native theme.js build(), src/ui/variant.js, the switch/call sites) — each with a v1 value that reproduces today EXACTLY, so v1 does not move by one pixel, one computed style, one DOM node or one host prop. Where a vibe branch (iron-age, navy, oxblood) already added a seam for the same thing, adopt its name and shape if it is sound (say so), so their merges reconcile.
 (a) colors.knob — the toggle's OFF knob (or: 'colors.steel' so v1 resolves steel): web .tog::after background; native src/ui/coach/settings.jsx ~139 thumbColor (off) and any other Switch site. [meet-day E1 BLOCKING, ledger R-3]
 (b) colors.greetName — the ink of the name in the You greeting (or: 'colors.accent'): web the greeting's name span (add a class if it has none, v1 styles unchanged); native youHero. [clear-sky R2, ledger R-1, Chalk's judge]
 (c) type.tag — a small-caps/tag preset (dflt null: every site keeps its v1 literal size/case/tracking) for the literal-caps and sub-11pt sites outside the blocks: the add-tile .tag (8.5px), .sync-pip, .trial-bar, .adm-flag, .conf, .ai-cost, .group-pill, auth.css's caps rules, MiniStats labels, .chart-sub/ChartSub, .you-since, the plate chip's figures, the calendar legend/day numbers; and a way for the preset sites that show lower-case strings as caps today (steps.js ~192 'to go'/'goal met', food.js ~604 'kcal left today'/'kcal over target', food.js ~3258 'kcal / day', workout.js ~1408 'bar only') to follow it. Web: the sites read var(--…) custom properties whose v1 values are today's literals; native: the sites read T.text.tag ?? today's literal. [meet-day E11, clear-sky R3+R6, ledger R-6, Chalk's request 7]
 (d) the two side stripes no block reaches — the tour tip (auth.css .ob-tip; native TourOverlay.jsx ~105) and the native Coach asking bubble (src/ui/coach/sheets.jsx ~468; web twin) — as a shape param (e.g. shape.stripe: 'side' | 'top' | 'keyline', v1 'side') so a vibe can draw a top rule or a full keyline on both clients. [clear-sky R4, ledger R-4]
 (e) shape.rule.hair may be 0 (the contract's paramOk currently demands > 0). [clear-sky R5]
 (f) the hero numeral: vocab headline gains look 'solo' (deep: the tab's one figure alone, large, in type.hero) and look 'bare' (the figure alone in its numeral type with the unit re-set in type.meta, sentence case); ROLES gains type.hero (kind type, native text.hero, or: 'type.headline'); a hero mark at the sites — web: Fuel's summary .load-num, Steps' today .load-num, the Goal's headline value (selectors/classes only; the inline JS sizes a deep vibe may beat are §5.9's); native: a hero prop at the same call sites (HeadlineV etc.), v1 identical. [clear-sky R1 — its concept depends on it; meet-day E5]
 (g) chart·ink wording + hooks: no area fill under the pinned lineChart (web: a scoped fill:none hook that a vibe's CSS can use; native: the line chart's area drawn only when the look says so), square line caps, legend keys drawable as 12×3 strokes. [clear-sky R7, ledger R-9, meet-day E6a]
 (h) card·ruled lead-card hooks on the web (Weight's log card, Steps' today card get a class/attribute marking them as the tab's lead card) and the tour card staying boxed under card·ruled on both clients. [clear-sky R8, ledger, iron-age]
 (i) kpi·word with pills kept (tint.pill* > 0): the pill's literal 11.5/10px delta type follows a role (e.g. type.pill, or: today's literal). [ledger R-11]
 (j) a native site for shape.rule.total (the web has one). [ledger R-12]
 (k) a native non-colour "chosen" cue for onboarding's choice cards (a drawn tick, as the web can do), off in v1. [ledger R-5]
 (l) NAME in vocab.js (wording only; each vibe draws its own look at the switch sites): kpi·lane, youHero·joined, statRow·board (inside a card: the strip runs to the card's edges, fallback cells on well within the padding), listRow·board (a leaderless board row, value in the numeral cut, record rows in shape.keyline), listRow·ledger's record rows (recap PR hits, Stats PR rows, Strongest lifts) taking shape.keyline and an optional leading rank numeral column, sessionChrome·slab's inverted slot as a param (v1 value = today's), setRow·attempt's coach state = warn, chart·board (rings as ten cells with board gaps, the target tick only where v1 draws a target). Confirm in the wording: sectionHeader·rule sets its title in type.h3; dock·rail's bar, segmented·tabs' underline and calCell·ruled's today keyline are drawn in accent. [meet-day E3-E10, E13; ledger R-7, R-8, R-10]
NOT in engine v3 (list them, don't build): meet-day's composition (a compose role + hooks X1-X7 = Phase X, its own branch later); meet-day E12 (the inversion exemption — Micah's policy call); the web tint.* custom properties / a bar rgb channel (clear-sky ask 9: each vibe writes its tints as hand rules for now).
Do NOT register any vibe and do NOT add any vibe's own files — that is each vibe's build. The contract's pure files stay byte-identical across the trees (copyFileSync) with updated pins.`

phase('Contract')
const contract = await agent(`${PREAMBLE}${PLAN}${ASKS}
===== YOUR JOB: the CONTRACT part of engine v3 =====
Worktrees: web ${WEB} (branch vibes/engine3 from web main b99ec9d), native ${NAT} (branch vibes/engine3 from native main f3382d3; node_modules is a symlink — never stage it). Make every contract change (vibes/defs/v1.js — new roles with today's values; vibes/defs/index.js — ROLES entries with or-fallbacks, paramOk for rule.hair ≥ 0, LEGACY_EXACT only if a new role needs an exact v1 spelling; vibes/defs/vocab.js — the new looks and wording of (f), (g), (l), the stripe param of (d); vibes/icons/v1.js only if a legend-key or tick glyph must be named) in the WEB tree; update tools-check/vibes-contract.mjs and tools-check/vibes-css.mjs if new custom properties must be generated (v1's rack.css :root then needs the same tokens with today's values — add them there, v1 unchanged); then copy the four pure files byte for byte to native src/pure/vibes/…, update native's pins (tools/verify-vibes-verbatim.mjs) and verify-vibes-contract. Make sure the registered Chalk still passes every contract check (its definition may leave the new roles out: valueOf() falls back). Run both contract verifiers and both suites in UTC. Commit on both branches ("Engine v3 (WIP): the contract" / "engine3(wip): the contract (V59 §9-§12)"). Return the new pins and the exact list of roles/looks/params added with their v1 values.`,
  { label: 'ev3:contract', phase: 'Contract', schema: { type: 'object', properties: { web_commit: { type: 'string' }, native_commit: { type: 'string' }, pins: { type: 'object' }, roles_added: { type: 'array', items: { type: 'string' } }, suite_utc: { type: 'string' }, left: { type: 'array', items: { type: 'string' } } }, required: ['web_commit', 'native_commit', 'pins', 'roles_added', 'suite_utc', 'left'] }, effort: 'high' })
if (!contract) return { error: 'contract agent failed' }

phase('Engines')
const REPORT = { type: 'object', properties: { commit: { type: 'string' }, done: { type: 'array', items: { type: 'string' } }, proof: { type: 'string' }, suite_utc: { type: 'string' }, left: { type: 'array', items: { type: 'string' } } }, required: ['commit', 'done', 'proof', 'suite_utc', 'left'] }
const WEB_PROOF = `Prove v1 unchanged, TWO ways: (1) against today's main, which is v1 and carries the same Settings hub and Chalk: \`node ${HARNESS} --a ${REF} --b ${WEB} …\` (${REF} is a clean detached checkout of web main b99ec9d; read the harness header for the --expect-vibe value when both trees serve /vibe.js) on EVERY scene at 390 and 320, data-vibe absent and --data-vibe v1 — expect 0 differences in every class (any difference is engine v3's and must be explained away or fixed); (2) touch-target 408/408 and the web suite in UTC. Also wear Chalk (--vibe chalk) A=${REF} vs B=${WEB} on every scene: 0 differences (Chalk leaves the new roles to their fallbacks, so it must not move either).`
const engines = await parallel([
  () => agent(`${PREAMBLE}${PLAN}${ASKS}\nThe contract agent reported: ${JSON.stringify(contract)}
===== YOUR JOB: the WEB engine part of engine v3 =====
Worktree ${WEB} (branch vibes/engine3; the contract commit is there). Implement every web-side ask: rack.css/auth.css base rules that SPEND the new roles through custom properties (so a vibe's generated token block moves them) with v1 values equal to today (single-level :root literals, identical spellings, the verifier-asserted lines untouched, no [data-vibe] in rack.css), the knob, the greeting-name class + rule, the tag preset at every listed literal site, the stripe param at the tour tip / Coach ask bubble, the hero mark classes (Fuel/Steps .load-num, Goal headline value), the chart·ink hooks (area fill, caps, legend keys), the lead-card marks, the pill type role. Page-module edits only add a class/attribute and never change text or order. ${WEB_PROOF} Commit "Engine v3 (WIP): the web engine".`, { label: 'ev3:web', phase: 'Engines', schema: REPORT, effort: 'high' }),
  () => agent(`${PREAMBLE}${PLAN}${ASKS}\nThe contract agent reported: ${JSON.stringify(contract)}
===== YOUR JOB: the NATIVE engine part of engine v3 =====
Worktree ${NAT} (branch vibes/engine3; the contract commit is there). Implement every native-side ask in theme.js build() (pass the new roles through; v1 values = today's) and at the sites: the Switch off-knob, youHero's name ink, T.text.tag at the literal sites (?? today's literal), the stripe param at TourOverlay/Coach ask bubble, the hero prop at HeadlineV and the Fuel/Steps figures, the line chart's area/caps/legend keys under chart·ink, a native site for shape.rule.total, the onboarding chosen tick (off in v1), the pill type role, the tour card boxed under card·ruled. Each new switch site goes in verify-vibe-seams' SITES; every v1 branch stays today's JSX. No new dependency. Prove v1 unchanged: verify-vibe-v1 byte-identical (baseline + the committed Settings-hub overlay only; re-baseline NOTHING), verify-theme-identity --require-build, verify-theme-build (extend it for each new role, red on a planted mistake), verify-vibe-seams, verify-vibe-parity + verify-vibe-fit (Chalk must still pass unchanged), the lints, the native suite in UTC. Commit "engine3(wip): the native engine (V59 §9-§12)".`, { label: 'ev3:native', phase: 'Engines', schema: REPORT, effort: 'high' }),
])
phase('Check')
const check = await agent(`${PREAMBLE}${PLAN}${ASKS}\nReports: contract ${JSON.stringify(contract)}; engines ${JSON.stringify(engines)}
===== YOUR JOB: check engine v3 (one round; findings need a reproduction) =====
Worktrees ${WEB} and ${NAT} (read-only for you). Confirm: v1 unchanged on both (re-run the proofs the builders claim: at least the native snapshot, and 12 web scenes at both widths A=${REF} B=${WEB}, absent + data-vibe v1 + --vibe chalk); the four pure files byte-identical across trees and pinned; every ask (a)-(l) implemented or explicitly listed as not (name which spec needs it and whether that vibe can ship without it); the new roles reach both clients (native build() output and the web generated block) for a scratch vibe that sets them (write it under ${NIGHT}/tmp, never register it). Classify: must-fix (v1 or Chalk moved, a proof red, an ask marked blocking missing) vs listed-not-fixed.`,
  { label: 'ev3:check', phase: 'Check', schema: { type: 'object', properties: { must_fix: { type: 'array', items: { type: 'string' } }, listed_not_fixed: { type: 'array', items: { type: 'string' } }, asks_status: { type: 'array', items: { type: 'string' } } }, required: ['must_fix', 'listed_not_fixed', 'asks_status'] }, effort: 'high' })
let fix = null, recheck = null
if (check && check.must_fix.length) {
  phase('Engines')
  fix = await agent(`${PREAMBLE}${PLAN}${ASKS}\n===== YOUR JOB: fix engine v3's must-fix items (one round) =====\nWorktrees ${WEB}, ${NAT}. Items: ${JSON.stringify(check.must_fix)}. For each: reproduce, fix, show the proof/check that found it passes; keep v1 and Chalk unchanged (native snapshot byte-identical; web prove A=${REF} 0 differences on the scenes touched, absent/data-vibe v1/--vibe chalk) and the suites green in UTC. Commit on the branch(es) touched ("Engine v3 (WIP): what the check found" / "engine3(wip): what the check found (V59 §9-§12)").`, { label: 'ev3:fix', phase: 'Engines', schema: REPORT, effort: 'high' })
  if (fix) {
    phase('Check')
    recheck = await agent(`${PREAMBLE}${PLAN}${ASKS}\n===== YOUR JOB: re-check engine v3 after its fix round =====\nThe check found: ${JSON.stringify(check.must_fix)}. The fixer reported: ${JSON.stringify(fix)}. Worktrees ${WEB}, ${NAT} (read-only). Re-run, in full: native verify-vibe-v1 + theme identity --require-build + the native suite in UTC; web prove A=${REF} B=${WEB} on EVERY scene at 390 and 320, absent and --data-vibe v1 and --vibe chalk (0 differences); the web suite in UTC. Confirm each must-fix item is fixed. Report must_fix (anything still wrong) and listed_not_fixed.`,
      { label: 'ev3:recheck', phase: 'Check', schema: { type: 'object', properties: { must_fix: { type: 'array', items: { type: 'string' } }, listed_not_fixed: { type: 'array', items: { type: 'string' } }, asks_status: { type: 'array', items: { type: 'string' } } }, required: ['must_fix', 'listed_not_fixed', 'asks_status'] }, effort: 'high' })
  }
}
return { contract, engines, check, fix, recheck }
