export const meta = {
  name: 'v59-proof-tooling-2',
  description: 'V59 §7 proof tooling, resumed: finish the web harness (partial work on disk) + its skeptic; fix the native proof\'s 10 blind spots + re-skeptic',
  phases: [
    { title: 'Build', detail: 'web harness (report/btn-44) and native verify-vibe-v1 + verify-theme-identity' },
    { title: 'Skeptic', detail: 'plant a known one-value change; the tool must catch it' },
    { title: 'Fix', detail: 'close any blindness, re-test' },
  ],
}

// @@PREAMBLE@@

const NIGHT = '/Users/micahflunker/dev/vibes-night'
const PROMPT = `${NIGHT}/VIBES-PROMPT.md`
const CODEMAP = `${NIGHT}/VIBES-CODEMAP.md`

const WEB_JOB = `
===== YOUR JOB: the web v1 proof harness (V59 §7.1) =====
Read first: ${PROMPT} §7 (lines 790-889) in full, §3 "Long commands" (lines 284-287), §13.3 (lines 1140-1146), §15.2 (lines 1262-1269). Codemap ${CODEMAP}: Web styling §9 "Proving v1 is identical" (lines 342-349) and Tooling §3 (lines 1343-1371). Then read the harness: report/btn-44/{measure.mjs, helpers.js, seed.mjs, diff.mjs, scenes.json, fakes/*} and report/btn-44.md.

Your worktree: ${NIGHT}/wt/web-harness (branch vibes/harness at 928a65e). You commit ONLY under report/btn-44/ there. The BASE tree is ${NIGHT}/wt/web-base (detached at 928a65e) — read-only for you: never edit it or write into it (serve it as-is). A scratch copy you may edit for experiments: ${NIGHT}/wt/web-hmut (detached 928a65e) — restore it to clean when done (\`git -C ${NIGHT}/wt/web-hmut checkout -- .\` and delete any file you added).
The pinned Archivo: ${NIGHT}/tools/fonts/archivo/Archivo-wdth-wght.ttf, sha256 0e094a7d3c7c4c25cf1310c4b30014f1dae9332220b1c2c88f4fa996f0b05053 (assert it at startup). Chrome: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome (CHROME overrides). A working one-scene smoke harness you may crib from: ${NIGHT}/tools/harness-smoke.mjs.

BUILD:
1. Parametrise report/btn-44/measure.mjs: REPO, PORT, CDP_PORT (env or flags), a per-run --user-data-dir under ${NIGHT}/tmp/<run>; fail loudly on a bind error (python's "Address already in use"); serialise through the night's lock ${NIGHT}/harness.lock (create with O_EXCL, your pid inside; reclaim only if that pid is dead; remove on exit, including on errors/signals); keep its existing CLI and default behaviour working.
2. A two-tree proof runner (e.g. report/btn-44/prove.mjs + a shared lib file): serves REPO_A and REPO_B with \`python3 -m http.server <port> --bind 127.0.0.1 --directory <repo>\` on two ports (8765, 8766), one headless Chrome on CDP 9333 (flags as measure.mjs plus --use-mock-keychain). For each scene group × width: boot A, run the scene steps, capture; boot B identically, capture; compare.
   - Before measuring, ASSERT which tree each port serves: GET /vibe.js must be 404 on base and 200 on engine; the expected status per side is a CLI flag (the control expects 404/404).
   - Hold fixed on both sides: a fixed Date / Date.now / performance.now injected with Page.addScriptToEvaluateOnNewDocument (NOW = 2026-09-25T19:30:00-04:00, a Friday evening; let time advance deterministically if the app needs timers to fire, or freeze — whichever gives a stable control; document it); a seeded Math.random; Emulation.setTimezoneOverride America/New_York; stop animations (Emulation.setEmulatedMedia prefers-reduced-motion: reduce, and/or Animation.setPlaybackRate 0 after boot — pick what gives a stable control; document it); blur the active element (no caret); hide scrollbars.
   - Seed ONCE: generate seed.json with seed.mjs under TZ=America/New_York with its clock frozen at the same NOW (a node --import preload under ${NIGHT}/tools/ that fixes Date), written to ${NIGHT}/proof/seed/seed.json (never into a tree; seed.mjs may gain an env var for the output path and NOW, defaults unchanged). Both trees use that one file.
   - Fonts: pin Archivo locally. In the Fetch interception, answer the fonts.googleapis.com/css2?family=Archivo… request with a local @font-face (family 'Archivo', font-weight 300 900, font-stretch 62% 125%) whose src is a URL you also intercept and fulfil with the pinned TTF bytes, identically for both sides. Fail every other off-machine request (keep the Firebase fakes). Guard after boot with BOTH \`(await document.fonts.load('700 16px Archivo')).length > 0\` AND \`[...document.fonts].some(f => f.family.replace(/["']/g,'') === 'Archivo' && f.status === 'loaded')\` — fonts.check() alone passes when nothing loaded.
   - Also assert rack.css line 1 (the Archivo @import) is byte-identical between A and B.
   - Scenes: the existing 58 at 390 and 320px. Add ONLY the missing "summary" (the workout summary screen) and "live session with a drop set" scenes to scenes.json (read AGENTS.md's drop-set section in the base tree: a drop is a set with type 'D' and dp: 1 under its parent; add a second live-session variant to seed.mjs's output, e.g. liveDrop, used by a cfg flag). Check first that no existing scene already shows them.
   - Capture per scene and width: Page.captureScreenshot {format:'png', captureBeyondViewport:true}; a getComputedStyle dump of EVERY element and its ::before/::after (every property except custom properties --*), bounding rects, and SVG attributes (geometry attributes raw: d, points, x, y, cx, cy, r, rx, width, height, viewBox, transform, stroke-width…; paint attributes fill/stroke/stop-color: record the COMPUTED value, because the engine may move a hex from an attribute into a style — say so in the output). Key each element by a stable path (tag + nth-of-type chain).
   - Be efficient on an 8 GB machine: hash each element's dump; store the full dumps gzipped (zlib) per scene under ${NIGHT}/proof/<run>/; compare hashes first and emit detail only for differing elements. Compare screenshot bytes first; if they differ, decode with a small node PNG reader written with zlib only (no npm) and list every differing region (bounding boxes of differing-pixel clusters, with pixel counts). Output ${NIGHT}/proof/<run>/summary.json: per scene × width {pixelsEqual, diffRegions, styleDiffs (count + first 20 with element path/property/A/B), rectDiffs, svgDiffs, errors}. NEVER write proof output under report/ (Pages publishes it).
   - Modes for later phases (build now, test on base): --vibe <id> (sets localStorage 'rack:vibe' to <id> right after the harness's localStorage.clear(), before the app loads — inert on base); "shoot" (one tree, 390px, a named scene list → PNGs in an out dir, for the gallery and the judges; also the full list from §15.2: You, Train calendar, live session with a drop set, summary, Fuel day, the add-food sheet, the Coach sheet, Weight, Steps, the Settings hub, the Vibes sheet (skip if absent), sign-in); "fit" (one tree at 320 and 390: horizontal overflow — document scrollWidth > innerWidth and any element whose rect exceeds the viewport; clipped text in fixed-height boxes — elements with a fixed height or overflow hidden/clip whose scrollHeight > clientHeight+1 or scrollWidth > clientWidth+1 and that contain text, especially .coach-card (190/164), .btn, .chip; interactive targets under 44px tall — buttons/links/[role=button]/inputs, reusing helpers.measure's notion). Scene/width/group filters (--scenes, --groups, --widths) so a run can be sharded under Bash's 10-minute cap.
3. CONTROL FIRST: serve the base tree on BOTH ports (REPO_A = REPO_B = ${NIGHT}/wt/web-base, expected /vibe.js 404/404): every scene × both widths must give 0 pixel and 0 computed-style differences. If not, find the nondeterminism and remove it (document each fix). Run the full control TWICE. Runs are long: use Bash run_in_background writing ${NIGHT}/proof/<run>/run.log and poll it with Read, or shard by group/width. Record the timing per full run.
4. BASELINE: keep the control's A-side dumps and PNGs as the base baseline at ${NIGHT}/proof/web-base-baseline/ (gzipped), with a manifest (sha 928a65e, pinned Archivo sha256, NOW, TZ, Chrome version from /json/version).
5. COMMIT on vibes/harness, explicit paths under report/btn-44/ only (NEVER seed.json, never proof output): subject "The v1 proof harness: two trees, pixels and computed styles, a pinned Archivo"; body: what it holds fixed, the control numbers, how to run each mode; end with the line "Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>". Message via Write to ${NIGHT}/tmp/msg-harness.txt, then \`git -C <wt> commit -F <file>\`. The web verifier suite must stay 52/52 (you touch no verifier) — run tools-check once in UTC to confirm.
Return the exact commands for each mode, the control numbers (scenes × widths, pixel diffs, style diffs, per run), timings, determinism fixes, and anything you could not do.`

const NAT_JOB = `
===== YOUR JOB: the native v1 proof (V59 §7.3 host-prop snapshot and §7.4 theme identity) =====
Read first: ${PROMPT} §6 (lines 651-787) and §7.3-§7.6 (lines 843-877). Codemap ${CODEMAP}: Native styling §1, §2, §7 and "Engine seam §6" (lines 353-424, 530-555, 593-597), Screens §1 (lines 673-761). Then the code: tools/lib/rn-render.mjs, tools/verify-top-inset.mjs (its 12 screens and store stub), tools/verify-text-color.mjs, tools/verify-coach-surface.mjs, src/ui/theme.js, app/_layout.jsx, app/(app)/_layout.jsx, the tabs layout, src/ui/Dock.jsx, src/ui/Sheet.jsx, src/ui/settings/index.jsx, the Coach sheet, onboarding/Setup, app/(auth)/sign-in.jsx.

Your worktree: ${NIGHT}/wt/nat-proof (branch vibes/proof at 1cb6498; node_modules is a symlink — NEVER stage it; stage explicit paths only). The BASE tree: ${NIGHT}/wt/nat-base (detached 1cb6498, node_modules linked) — read-only for you. Scratch for experiments: ${NIGHT}/wt/nat-hmut (detached 1cb6498, linked) — restore it clean when done.

BUILD (in tools/, house style — read two existing verifiers first):
1. tools/verify-vibe-v1.mjs on tools/lib/rn-render.mjs. With a FROZEN clock (NOW = 2026-09-25T19:30:00-04:00) and any seed frozen, it mounts: verify-top-inset.mjs's 12 screens (You, Train, Fuel, Weight, Steps, Stats, one-lift Stats, Admin, Summary, Session idle, Session live, Recap), plus the Dock and the Tabs layout, SheetHost with the Settings hub open, the Coach sheet, a live session (with a drop set if the store stub allows), the Setup (onboarding) steps, and sign-in. BlurView, LinearGradient (expo-linear-gradient), StatusBar (expo-status-bar), DateTimePicker and ImageBackground as PROP-RECORDING stubs (hosts that appear in the dump with their props). Define the stubs in the verifier's own files (e.g. tools/lib/vibe-snap.mjs), not by editing rn-render, so the SAME verifier can render the base tree: take --root <tree> (default: its own tree) and load that tree's rn-render and sources.
   Dump for each host, in tree order: its type; its flattened style (canonical key order); its colour/SVG props (fill, stroke, stopColor, stopOpacity, placeholderTextColor, trackColor, thumbColor, ios_backgroundColor, keyboardAppearance, tint, intensity, colors, locations, start, end, style (StatusBar), themeVariant, source (ImageBackground), color, backgroundColor, selectionColor, cursorColor) and every other string/number/boolean prop (skip functions; skip non-deterministic values; if something is non-deterministic, freeze it and say how). Canonical JSON with sorted keys.
   Modes: default = render and compare with the committed baseline tools/vibe-v1.baseline.json, byte-identical, printing a readable diff (first N differing hosts with path/prop/before/after) on failure and exiting 1; --write-baseline = write the baseline including the sha it was captured at (\`git -C <root> rev-parse HEAD\`) and a per-screen host count.
   Time zones: the suite runs under TZ=America/New_York, UTC and Pacific/Auckland. Either make the dump zone-independent or pin the zone for the render (e.g. re-spawn under a fixed TZ) — choose, document why, and prove it passes in all three.
   CONTROL FIRST: render the base tree twice → identical; render your own tree (same code as base) → identical to base. Then write the baseline FROM THE BASE TREE (--root ${NIGHT}/wt/nat-base) and commit it.
2. tools/verify-theme-identity.mjs (§7.4). Load src/ui/theme.js the way rn-render does (compiled module, NOT by regex), so it survives the engine's refactor. Dump the pre-engine exports: every table (colors, tint, space, radius, layout constants, motion, text presets); alpha.* sampled on a grid of values (e.g. 0, .02, .05, .07, .1, .12, .14, .16, .18, .2, .25, .3, .4, .5, .6, .8, .82, .9, 1); layout functions on a grid of safe-area insets (top/bottom 0, 20, 24, 44, 47, 48, 59; plus whatever keyboard/height args they take); all 20 text presets; face() for all 31 wdth×wght pairs used in the code (find them by AST; list them); type() for every argument set found at the ~155 call sites (AST scan with @babel/parser from node_modules over app/ and src/; literal object args evaluated; non-literal args listed as skipped with file:line); loadNum() for each size used (AST). Write tools/theme-v1.baseline.json at 1cb6498 (sha inside). The verifier compares the current theme.js default export against the baseline, deep-equal; AND, when theme.js exports build and src/pure/vibes/defs/v1.js exists, also build(v1) — say "build() not present yet" and pass otherwise.
3. DATA for the engine (do not commit lints): an AST scan written to ${NIGHT}/proof/nat-lint-baseline.json: (a) every colour literal outside src/ui/theme.js (hex, rgb/rgba, named colours except 'transparent'), excluding the pinned pure files; (b) every module-scope \`T.\` read (file:line, what); (c) every \`T\` reference inside a worklet (useAnimatedStyle / useDerivedValue / useAnimatedProps callbacks, interpolateColor args inside them, functions with a 'worklet' directive). Compare the counts with the codemap's (14 files / 76 module-scope refs; 45 hex literals in 12 files; 9 rgba sites; 2 worklet sites) and explain differences.
4. RUN the full native suite in three zones via \`node ${NIGHT}/tools/run-verifiers.mjs nat ${NIGHT}/wt/nat-proof ${NIGHT}/proof/natproof-suite\` — 83/83 (81 + your 2), batteries unchanged.
5. COMMIT on vibes/proof (explicit paths; message via Write to ${NIGHT}/tmp/msg-natproof.txt; \`git -C <wt> commit -F <file>\`): subject "tools: the v1 proof — host props over N screens, and theme identity, baselined at 1cb6498 (V59 §7)"; body with screens covered, host count, the TZ decision; end with "Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>".
Return: screens covered and host counts, the control result, run commands, the lint-baseline counts vs the codemap, anything not coverable and why.`

const WEB_SKEPTIC = `
===== YOUR JOB: skeptic of the web v1 proof harness =====
The harness in ${NIGHT}/wt/web-harness/report/btn-44/ (branch vibes/harness) claims: served two trees, it reports every pixel and computed-style difference, and base-vs-base gives 0/0. A harness that cannot see a real difference would let a broken engine through. Try to show it is BLIND. Use the scratch worktree ${NIGHT}/wt/web-hmut (detached 928a65e; you may edit it; restore it clean at the end — \`git -C ${NIGHT}/wt/web-hmut checkout -- .\` and delete added files; verify with git status). Plant, one at a time, small real differences in web-mut and run the harness with A = ${NIGHT}/wt/web-base, B = ${NIGHT}/wt/web-hmut on a few scenes (use its scene filters; expected /vibe.js 404/404 — or add an empty vibe.js to web-mut to test the port assertion too): (1) --dim #5c6270 → #5c6271 in rack.css :root (a 1-unit colour change); (2) a 1px padding change on a common card rule; (3) one SVG path char in a dock icon in index.html; (4) a letter-spacing .02em → .021em on a label; (5) a ::before/::after content or colour change; (6) swap one hex in an inline style set by JS (e.g. a plate colour in workout.js) for its rgb() equivalent — this one must report ZERO differences (same computed value), proving the harness compares computed values, not source text. For 1-5 the harness must report a difference (pixel and/or style) in an affected scene. Also check: the port assertion really fails when a side serves the wrong tree; the Archivo guard really fails if the font is blocked (point the pinned path at a missing file in a scratch copy of the harness under ${NIGHT}/tmp/ rather than editing the committed one); the lock works (a second run refuses while one holds it). The harness holds ${NIGHT}/harness.lock — never run two at once. Report each probe: planted change, scenes run, what the harness reported, pass/blind.`

const NAT_SKEPTIC = `
===== YOUR JOB: skeptic of the native v1 proof =====
tools/verify-vibe-v1.mjs and tools/verify-theme-identity.mjs in ${NIGHT}/wt/nat-proof (branch vibes/proof) claim to catch any change to v1's host props / theme exports. Try to show they are BLIND. Use the scratch worktree ${NIGHT}/wt/nat-hmut (detached 1cb6498, node_modules linked; restore clean at the end — \`git -C ${NIGHT}/wt/nat-hmut checkout -- .\`, delete added files, check git status). Plant, one at a time, in nat-mut: (1) T.colors.dim #5c6270 → #5c6271 in theme.js; (2) one tint alpha .14 → .15; (3) a padding 14 → 15 in one screen component; (4) a Dock icon path char; (5) Settings hub: one row's label colour; (6) BlurView intensity 40 → 41 in Dock.jsx; (7) sign-in: one literal hex; (8) a text preset's letterSpacing. Run \`node ${NIGHT}/wt/nat-proof/tools/verify-vibe-v1.mjs --root ${NIGHT}/wt/nat-hmut\` (and the theme-identity verifier against nat-mut the same way, if it supports --root; if it doesn't, that is itself a finding to fix — it must be able to judge a tree other than its own) and confirm each goes red with a readable diff. Also: does a change in a screen NOT in its list go unseen? Name the screens/hosts it cannot see (e.g. screens behind navigation it never mounts) — list them as coverage gaps (not failures). Report each probe: planted change, result, pass/blind.`

const SKEPTIC_SCHEMA = {
  type: 'object',
  properties: {
    probes: { type: 'array', items: { type: 'object', properties: {
      change: { type: 'string' }, ran: { type: 'string' }, reported: { type: 'string' }, verdict: { type: 'string', enum: ['caught', 'blind', 'correctly-zero', 'wrongly-nonzero', 'could-not-run'] } },
      required: ['change', 'ran', 'reported', 'verdict'] } },
    coverage_gaps: { type: 'array', items: { type: 'string' } },
    scratch_restored_clean: { type: 'boolean' },
    summary: { type: 'string' },
  },
  required: ['probes', 'coverage_gaps', 'scratch_restored_clean', 'summary'],
}
const BUILD_SCHEMA = {
  type: 'object',
  properties: {
    commit: { type: 'string' },
    commands: { type: 'object', description: 'mode -> exact command' },
    control: { type: 'string', description: 'the control numbers, per run' },
    baseline_location: { type: 'string' },
    counts: { type: 'object', description: 'scenes/screens, widths, hosts, verifier suite results' },
    determinism_fixes: { type: 'array', items: { type: 'string' } },
    not_done: { type: 'array', items: { type: 'string' } },
    notes: { type: 'string' },
  },
  required: ['commit', 'commands', 'control', 'baseline_location', 'counts', 'determinism_fixes', 'not_done', 'notes'],
}

const RESUME_WEB = `
===== RESUMING (second time: it died again at the next usage limit — keep committing WIP as you go): a previous builder hit the account's session limit mid-work =====
It left UNCOMMITTED work in ${NIGHT}/wt/web-harness: report/btn-44/{measure.mjs, helpers.js, scenes.json, seed.mjs} modified; report/btn-44/{capture.js, harness-lib.mjs, prove.mjs, shoot.json} new. Nothing was committed. First read every one of those files and \`git -C ${NIGHT}/wt/web-harness diff\` in full, judge what is done and sound, and CONTINUE from there (keep what is right, fix what isn't) rather than starting over. Check for leftovers of its runs: ${NIGHT}/harness.lock (the resume check found none), ${NIGHT}/proof/* run dirs it may have started (reuse or ignore; don't delete other agents' files), ${NIGHT}/proof/seed/seed.json (if present, verify it was generated with the frozen NOW before reusing it). Then finish every item of the job below and commit — commit a WIP after every coherent sub-step (a usage limit can end your session without warning). KNOWN PRE-EXISTING RED (not yours to fix; don't touch it): the rate-band verifier (native tools/verify-rate-band.mjs, web tools-check/rate-band.mjs) currently FAILS under TZ=Pacific/Auckland on the UNTOUCHED base trees (1cb6498 / 928a65e) — New Zealand's daylight saving starts 27 Sep 2026. Treat an Auckland rate-band failure as acceptable ONLY if the base tree (/Users/micahflunker/dev/vibes-night/wt/nat-base or wt/web-base) fails it the same way when run right after, in the same zone; report both results. `

const NAT_FIX = `
===== YOUR JOB: fix the native v1 proof's blind spots (round 1) =====
The native proof tools are built and committed on ${NIGHT}/wt/nat-proof (branch vibes/proof, commit 260055f): tools/verify-vibe-v1.mjs + tools/lib/vibe-snap.mjs + tools/lib/vibe-seed.mjs + tools/vibe-v1.baseline.json, and tools/verify-theme-identity.mjs + tools/theme-v1.baseline.json. The builder's report: ${NIGHT}/proof/natproof/build-report.json. A skeptic then planted real differences in ${NIGHT}/wt/nat-hmut and found these BLIND spots and coverage gaps — read ${NIGHT}/proof/natproof/skeptic-r1.json in full.
Fix the tools so each blind probe is caught, then re-run the CONTROL (base rendered twice identical; own tree identical to base) and re-capture the baselines FROM THE BASE TREE (${NIGHT}/wt/nat-base, clean, at 1cb6498) only if the dump format changed. Specifically:
1. theme identity must not pass vacuously: when theme.js exports build, REQUIRE src/pure/vibes/defs/v1.js (fail if missing, don't skip), and prove build() closes over the tokens it is given — call build() with a mutated copy of the v1 def (e.g. chalk, a tint alpha, a text size, the face family) and require the outputs to CHANGE accordingly (colors, text presets' colour, tint strings, type() default colour, face()), and with the real v1 def to equal the baseline.
2. --write-baseline refuses a dirty tree (git status --porcelain non-empty, ignoring the node_modules symlink) and records the tree's HEAD; the default check ALSO verifies the baseline's own sha256 against a pin in the verifier (or the baseline's capturedAt against 1cb6498 and a content hash), so a tree under test cannot quietly re-capture its own baseline.
3. Load app/_layout.jsx (the root layout) and app/(app)/_layout.jsx FIRST in both passes, before any screen, as on a phone — so module-scope side effects in the layouts (e.g. applyTheme at boot) show up in every scene.
4. Pressable children written as functions: render them for pressed:false AND pressed:true (like sp for style functions) at food.jsx:148/150, workout/summary.jsx:248, coach/sheets.jsx:501, food/common.jsx:838 and any other site (find them by AST).
5. States and sheets no scene draws: add scenes for as many of the skeptic's coverage gaps as the store stub allows — at least: the Settings hub with a refused save; openRecallList, openLiveSheet (Coach during a session), openAiSettings, openBarGuide, the scan route, openItemEdit, openLibrary, openPortion, openManual, openMealsSheet, openMealBuilder, openImportPaste, openWaterSettings, openRefused, a confirmSheet, openSetSteps, openExerciseManager, openExerciseEdit, openCustomExercise, openStatsPicker; KeypadDoneBar shown; SyncPip offline; DevAccountBanner; paused with an expired trial; the trial bar near expiry; FeelCard with a chip picked; Swipe revealed; SetRow's tick flash colour (record the worklet's colour inputs/outputs at flash 0 and 1); the dock focused on each tab. Record animation configs (durations/easings) in the dump.
6. Geometry: add a second pass at a different geometry (e.g. width 320, insets 20/0, fontScale 1.353) for a representative subset of scenes (all tabs + Settings + Coach card + a sheet), so inset/fontScale/width branches are checked.
7. Make each diff line name the host's text (first Text descendant) so a reader can tell which row changed.
Say explicitly which gaps you could NOT close and why (they go in the report's "unsure" list). Keep the suite green: run \`node ${NIGHT}/tools/run-verifiers.mjs nat ${NIGHT}/wt/nat-proof ${NIGHT}/proof/natproof-fix1-suite\` — 83/83 ×3 zones. Commit on vibes/proof as a NEW commit: subject "tools: the v1 proof — what the skeptic found (V59 §7)"; body lists each blind probe and how it is now caught, scenes/hosts before→after, what stays uncovered; end with "Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>". Use ${NIGHT}/wt/nat-hmut as your scratch for planting the skeptic's probes again (restore it clean).`

const TRACKS = [
  { key: 'web', job: RESUME_WEB + WEB_JOB, skeptic: WEB_SKEPTIC, wt: `${NIGHT}/wt/web-harness` },
  { key: 'nat', job: NAT_FIX + '\n\nFor reference, the original build brief:\n' + NAT_JOB, skeptic: NAT_SKEPTIC, wt: `${NIGHT}/wt/nat-proof`, fixFirst: true },
]

const out = await pipeline(TRACKS,
  t => agent(`${PREAMBLE}${t.job}`, { label: t.fixFirst ? `fix:${t.key}-r1` : `build:${t.key}`, phase: t.fixFirst ? 'Fix' : 'Build', schema: BUILD_SCHEMA }),
  async (built, t) => {
    if (!built) return { key: t.key, built: null }
    let sk = await agent(`${PREAMBLE}${t.skeptic}\n\n${t.fixFirst ? 'This is a RE-TEST after a fix. The previous skeptic round is in ' + NIGHT + '/proof/natproof/skeptic-r1.json — re-run EVERY probe in it (blind ones especially) plus your own new ones.' : ''}\nThe builder reported:\n${JSON.stringify(built, null, 1)}`, { label: `skeptic:${t.key}${t.fixFirst ? '-r2' : ''}`, phase: 'Skeptic', schema: SKEPTIC_SCHEMA })
    const history = [sk]
    for (let round = 1; round <= 2 && sk && sk.probes.some(p => p.verdict === 'blind' || p.verdict === 'wrongly-nonzero'); round++) {
      const bad = sk.probes.filter(p => p.verdict === 'blind' || p.verdict === 'wrongly-nonzero')
      log(`${t.key}: skeptic found ${bad.length} blind spots; fixing (round ${round})`)
      const fixed = await agent(`${PREAMBLE}${t.job}\n\n===== YOU ARE THE FIXER (round ${round}) =====\nThe tool above is built and committed in ${t.wt}. A skeptic planted real differences and the tool missed or mis-reported these:\n${JSON.stringify(bad, null, 1)}\nReproduce each in the scratch worktree the skeptic used (restore it clean after), fix the tool so it catches them, re-run the CONTROL (it must stay 0/0 / identical), and commit the fix on the same branch as a new commit (subject: web "The v1 proof harness: what the skeptic found"; native "tools: the v1 proof — what the skeptic found (V59 §7)"; Co-Authored-By line at the end).`, { label: `fix:${t.key}-r${round}`, phase: 'Fix', schema: BUILD_SCHEMA })
      if (!fixed) break
      sk = await agent(`${PREAMBLE}${t.skeptic}\n\nThis is a RE-TEST after a fix. Re-run every probe, especially these, which were blind before:\n${JSON.stringify(bad, null, 1)}`, { label: `skeptic:${t.key}-r${round + 1}`, phase: 'Skeptic', schema: SKEPTIC_SCHEMA })
      history.push(sk)
    }
    return { key: t.key, built, skeptic: history }
  })
return out
