#!/usr/bin/env node
//
// Verifier for which maintenance number the app quotes.
//
//   node tools-check/maintenance.mjs
//
// The precedence used to be hand-copied into Fuel, You and Weight. It is one
// function now — effectiveMaint() in tdee.js — and this drives the REAL one,
// along with the two pure cores in food.js that decide what Save writes
// (maintPatch) and when auto targets are allowed to move (autoPlan). No copy of
// any of that logic lives in here; a verifier with its own copy stops being
// true the moment the file it checks changes.
//
// What it proves:
//   - the four-way precedence: pinned, measured, setup, and "we don't know";
//   - an ABSENT maintSrc reads as pinned, so none of the eight accounts that
//     predate the key has its number moved by this ship;
//   - a setup number expires the moment there is a measured estimate, and
//     comes BACK if that estimate is later lost — nothing is rewritten;
//   - opening Daily targets and saving it untouched leaves a setup number a
//     setup number, which is the bug that would otherwise turn every guess
//     into a pin the first time somebody edited their protein;
//   - typing a number pins it, blanking it clears both keys;
//   - and a setup number expiring cannot move the calorie target outside the
//     weekly gate, however far maintenance jumps.
//   - v57 (SHIP-V57-PROMPT §B): the note under the calorie bar is true of the
//     numbers it names — Micah's own case (maintenance 3,220, target 3,470, a
//     gain) first, then every target across a grid of maintenances, both goals.
//   - v58 (SHIP-V58-PROMPT §B): the band capped at 200, not 250 — his case
//     before (rack-v57's tdee.js, from git) and after; every maintenance from
//     1,500 to 4,500 with Rack's three preset targets, and which of them
//     change colour; and "Reading the bar"'s two sentences about the yellow,
//     held to their numbers in pounds and in kilos.

import { mkdtempSync, writeFileSync, readFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const SRC  = p => join(HERE, '..', p);

/* ---------- the fake browser ----------
   store.js touches four globals at load and food.js touches none until it is
   called. Nothing below renders, so this is the whole of it. */

const cells = new Map();
globalThis.localStorage = {
  getItem: k => (cells.has(k) ? cells.get(k) : null),
  setItem: (k, v) => cells.set(k, String(v)),
  removeItem: k => cells.delete(k),
  key: i => Array.from(cells.keys())[i] ?? null,
  get length() { return cells.size; }
};
globalThis.window = { addEventListener() {} };
globalThis.document = { body: null, getElementById: () => null, createElement: () => ({ style: {} }) };
try {
  Object.defineProperty(globalThis, 'navigator', {
    value: { onLine: true }, configurable: true, writable: true
  });
} catch { /* Node may own it; nothing here reads it */ }

/* ---------- staging ----------

   The modules whose real code is under test are copied as-is with their
   relative imports repointed at each other. Everything else any of them
   imports — the Firebase SDK, the estimator, Water, Recall, usage counters —
   becomes one generated stub, because none of it is reachable from a pure
   function and loading it would drag the whole app into a unit test.

   The stub's exports are generated by reading the import statements rather
   than by listing names here, so a new import in food.js does not silently
   break this file with "does not provide an export named". */

const REAL = ['store.js', 'ui.js', 'units.js', 'weightmodel.js', 'tdee.js', 'food.js'];
const IMPORT_RE = /\bfrom\s+(['"])([^'"]+)\1/g;
const NAMED_RE  = /\bimport\s*\{([^}]*)\}\s*from\s+(['"])([^'"]+)\2/g;

const sources = new Map(REAL.map(f => [f, readFileSync(SRC(f), 'utf8')]));
const stubbed = new Set();

for (const text of sources.values()) {
  let m;
  NAMED_RE.lastIndex = 0;
  while ((m = NAMED_RE.exec(text))) {
    const spec = m[3];
    const base = spec.startsWith('./') ? spec.slice(2) : null;
    if (base && REAL.includes(base)) continue;
    for (const raw of m[1].split(',')) {
      // `forget as recallForget` — the stub has to export `forget`, the name on
      // the left. Taking the local binding instead is how this fails with
      // "does not provide an export named".
      const name = raw.trim().split(/\s+as\s+/)[0].trim();
      if (name) stubbed.add(name);
    }
  }
}

// Every stubbed name is a callable that returns undefined. That is enough:
// store.js calls initializeApp/getAuth/getDatabase at load and nothing else in
// here reaches a stub, so a stub that is ever actually USED by a test would
// show up as a wrong answer rather than as a pass.
const stub = Array.from(stubbed)
  .map(n => `export function ${n}() {}`)
  .join('\n') + '\n';

const dir = mkdtempSync(join(tmpdir(), 'rack-maint-'));
writeFileSync(join(dir, 'stub.mjs'), stub);
const repoint = text => text.replace(IMPORT_RE, (whole, q, spec) => {
  const base = spec.startsWith('./') ? spec.slice(2) : null;
  return base && REAL.includes(base)
    ? `from './${base.replace(/\.js$/, '.mjs')}'`
    : `from './stub.mjs'`;
});
for (const [file, text] of sources) writeFileSync(join(dir, file.replace(/\.js$/, '.mjs')), repoint(text));
// v58: rack-v57's tdee.js beside today's, the band capped at 250 — the before.
const V57 = 'f985823';
writeFileSync(join(dir, 'tdee57.mjs'),
  repoint(execFileSync('git', ['show', V57 + ':tdee.js'], { cwd: SRC('.'), encoding: 'utf8', maxBuffer: 1 << 26 })));

const load = f => import(pathToFileURL(join(dir, f)).href);
const { effectiveMaint, autoTargets, calorieZones, zoneOf } = await load('tdee.mjs');
const { maintPatch, autoPlan, targetNote, holdWords, markWords } = await load('food.mjs');
const { calorieZones: calorieZones57 } = await load('tdee57.mjs');

/* ---------- harness ---------- */

let pass = 0, fail = 0;
const results = [];
function check(name, ok, detail) {
  if (ok) { pass++; results.push('  ok   ' + name); }
  else    { fail++; results.push('  FAIL ' + name + (detail ? '  — ' + detail : '')); }
}
const shape = v => JSON.stringify(v);

// maintenance()'s return, narrowed to the one field effectiveMaint reads.
const EST   = tdee => ({ tdee, avgIntake: 2600, days: 12, rateWk: -0.4, need: [] });
const NOEST = { tdee: null, avgIntake: null, days: 3, rateWk: null, need: ['4 more days of food logging'] };

/* ---------- 1. the four-way precedence ---------- */

{
  const pinned = effectiveMaint({ maint: 2400, maintSrc: 'pinned' }, EST(2680));
  check('pinned beats a measured estimate',
    pinned && pinned.cal === 2400 && pinned.source === 'pinned' && pinned.auto === false,
    shape(pinned));

  const measured = effectiveMaint({ maint: 2400, maintSrc: 'setup' }, EST(2680));
  check('a setup number loses to a measured estimate',
    measured && measured.cal === 2680 && measured.source === 'measured' && measured.auto === true,
    shape(measured));

  const setup = effectiveMaint({ maint: 2400, maintSrc: 'setup' }, NOEST);
  check('a setup number is used while there is no estimate',
    setup && setup.cal === 2400 && setup.source === 'setup' && setup.auto === false,
    shape(setup));

  check('nothing stored and nothing measured is null, not a guess',
    effectiveMaint({ maint: null }, NOEST) === null);
  check('no targets node at all is null',
    effectiveMaint(null, null) === null && effectiveMaint(undefined, undefined) === null);
}

/* ---------- 2. the eight existing accounts do not move ----------
   No stored account has maintSrc. If absent read as "setup", every one of them
   would silently start quoting a different maintenance number on the morning
   this ships — including anyone who typed theirs on purpose. */

{
  const a = effectiveMaint({ maint: 2400 }, EST(2680));
  check('absent maintSrc reads as pinned, even with an estimate available',
    a && a.cal === 2400 && a.source === 'pinned', shape(a));

  const b = effectiveMaint({ maint: 2400, maintSrc: undefined }, EST(2680));
  check('an explicitly undefined maintSrc reads as pinned',
    b && b.source === 'pinned', shape(b));

  const c = effectiveMaint({ maint: 2400, maintSrc: null }, EST(2680));
  check('a null maintSrc reads as pinned', c && c.source === 'pinned', shape(c));

  // A value nobody wrote is not a licence to move somebody's number either.
  const d = effectiveMaint({ maint: 2400, maintSrc: 'SETUP' }, EST(2680));
  check('an unrecognised maintSrc reads as pinned, never as setup',
    d && d.source === 'pinned', shape(d));
}

/* ---------- 3. expiry, and coming back ----------
   Expiry is a read-side decision and nothing is rewritten, which is what makes
   it reversible: the same stored record answers differently as the model gains
   and loses its estimate. */

{
  const stored = { maint: 2400, maintSrc: 'setup' };
  check('setup + no estimate -> setup',
    effectiveMaint(stored, NOEST).source === 'setup');
  check('setup + estimate -> measured',
    effectiveMaint(stored, EST(2680)).source === 'measured');
  check('estimate lost -> back to setup, from the same stored record',
    effectiveMaint(stored, NOEST).cal === 2400 &&
    effectiveMaint(stored, NOEST).source === 'setup');
  check('the stored record was not mutated by any of that',
    shape(stored) === shape({ maint: 2400, maintSrc: 'setup' }), shape(stored));

  // The model's own sufficiency bar, not a second one invented here.
  check('a null tdee is not an estimate',
    effectiveMaint(stored, { tdee: null }).source === 'setup');
  check('a zero tdee is not a maintenance number',
    effectiveMaint(stored, { tdee: 0 }).source === 'setup');
  check('a NaN tdee is not a maintenance number',
    effectiveMaint(stored, { tdee: NaN }).source === 'setup');
  check('with no stored number and no usable estimate the answer is null',
    effectiveMaint({ maint: 0 }, { tdee: 0 }) === null);
}

/* ---------- 4. the Daily-targets sheet ----------
   The box is prefilled with a number somebody CHOSE and nothing else. These
   drive maintPatch() with the same (box, whatItOpenedWith, stored) the sheet
   passes it. */

{
  // THE ONE THAT MATTERS. A setup account opens the sheet to change its
  // protein; the maintenance box is empty because the setup number is a
  // placeholder, and Save must not touch either key.
  const stored = { maint: 2400, maintSrc: 'setup', cal: 2100, p: 190, f: 70 };
  const r = maintPatch('', '', stored);
  check('sheet saved untouched: a setup number stays a setup number',
    r.maint === 2400 && r.maintSrc === 'setup' && r.changed === false, shape(r));
  check('sheet saved untouched: the number in force is still the setup one',
    effectiveMaint({ ...stored, ...r }, NOEST).source === 'setup');
  check('sheet saved untouched: and still expires when the estimate arrives',
    effectiveMaint({ ...stored, ...r }, EST(2680)).source === 'measured');
}

{
  // The same for the accounts with no maintSrc: the box opens holding their
  // number, and an untouched Save must not stamp it 'pinned' either — that
  // would answer the one-time question on their behalf.
  const stored = { maint: 2400, cal: 2100 };
  const r = maintPatch('2400', '2400', stored);
  check('sheet saved untouched: an absent maintSrc stays absent',
    r.maint === 2400 && r.maintSrc === null && r.changed === false, shape(r));
}

{
  const stored = { maint: 2400, maintSrc: 'pinned' };
  const r = maintPatch('2400', '2400', stored);
  check('sheet saved untouched: a pinned number stays pinned',
    r.maint === 2400 && r.maintSrc === 'pinned' && r.changed === false, shape(r));
}

{
  const stored = { maint: 2400, maintSrc: 'setup' };
  const r = maintPatch('2550', '', stored);
  check('typing a number over a setup placeholder pins it',
    r.maint === 2550 && r.maintSrc === 'pinned' && r.changed === true, shape(r));
  check('a pinned number then beats the estimate',
    effectiveMaint({ ...stored, ...r }, EST(2680)).cal === 2550);
}

{
  const stored = { maint: 2400, maintSrc: 'pinned' };
  const r = maintPatch('', '2400', stored);
  check('typed then blanked: both keys cleared',
    r.maint === null && r.maintSrc === null && r.changed === true, shape(r));
  check('typed then blanked: the estimate takes over',
    effectiveMaint({ ...stored, ...r }, EST(2680)).source === 'measured');
  check('typed then blanked with no estimate: we genuinely do not know',
    effectiveMaint({ ...stored, ...r }, NOEST) === null);
}

{
  const stored = { maint: 2400 };
  check('editing an absent-maintSrc number pins it',
    shape(maintPatch('2500', '2400', stored)) === shape({ maint: 2500, maintSrc: 'pinned', changed: true }));
  check('junk in the box clears, the way parseInt always made it',
    shape(maintPatch('abc', '2400', stored)) === shape({ maint: null, maintSrc: null, changed: true }));
  check('zero clears rather than pinning a zero',
    shape(maintPatch('0', '2400', stored)) === shape({ maint: null, maintSrc: null, changed: true }));
  check('whitespace either side is not a change',
    maintPatch(' 2400 ', '2400', stored).changed === false);
  check('a sheet opened on an empty box and left empty writes nothing new',
    shape(maintPatch('', '', { maint: null })) === shape({ maint: null, maintSrc: null, changed: false }));
}

/* ---------- 5. auto targets and the weekly gate ----------
   A setup number expiring can move maintenance by hundreds of kcal in one
   render. The gate is what keeps the calorie target from following it there
   and then, and this is the proof that the gate is still in the path. */

const DAY = 864e5;
const NOW = 1_758_000_000_000;           // fixed: autoPlan takes its clock as an argument
const GOAL = { on: true, rateWk: -1, pPerLb: 1, fPerLb: 0.35, floor: 0, lastAdj: 0 };

{
  const before = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: NOW - 2 * DAY } };
  const jump = autoPlan(before, 2680, 190, NOW);
  check('maintenance jumping does not move the target two days after the last move',
    jump === null, shape(jump));

  const due = autoPlan({ ...before, auto: { ...GOAL, lastAdj: NOW - 8 * DAY } }, 2680, 190, NOW);
  check('the same jump moves it a week later', due !== null && due.cal > before.cal, shape(due));
  check('and moves it by at most one step',
    due && due.cal - before.cal <= 100, shape(due));
  check('and stamps the clock it was given, not one of its own',
    due && due.lastAdj === NOW, shape(due));
}

{
  // The boundary itself, in both directions.
  const at = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: NOW - 7 * DAY } };
  check('exactly seven days is due', autoPlan(at, 2680, 190, NOW) !== null);
  const just = { ...at, auto: { ...GOAL, lastAdj: NOW - 7 * DAY + 1000 } };
  check('a second short of seven days is not', autoPlan(just, 2680, 190, NOW) === null);
}

{
  const off = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, on: false, lastAdj: 0 } };
  check('auto targets switched off never move', autoPlan(off, 2680, 190, NOW) === null);
  check('no maintenance number, no move',
    autoPlan({ cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: 0 } }, 0, 190, NOW) === null);
  check('no trend weight, no move',
    autoPlan({ cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: 0 } }, 2680, 0, NOW) === null);
}

{
  // A never-adjusted account (lastAdj 0) is allowed to move, which is how the
  // first adjustment ever happens — the gate is "not recently", not "never".
  const fresh = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: 0 } };
  check('an account that has never adjusted is due', autoPlan(fresh, 2680, 190, NOW) !== null);

  // …and a move too small to be worth making is still not made.
  const settled = autoTargets(GOAL, 2680, 190);
  const sameish = { cal: settled.cal, p: settled.p, f: settled.f, auto: { ...GOAL, lastAdj: 0 } };
  check('a target already where the maths puts it does not churn',
    autoPlan(sameish, 2680, 190, NOW) === null, shape(autoPlan(sameish, 2680, 190, NOW)));
}

{
  // End to end: the day a setup number expires, nothing moves on render.
  const stored = { maint: 2400, maintSrc: 'setup', cal: 1900, p: 190, f: 67,
                   auto: { ...GOAL, lastAdj: NOW - DAY } };
  const was = effectiveMaint(stored, NOEST);
  const now = effectiveMaint(stored, EST(2680));
  check('the number quoted really did jump on expiry',
    was.cal === 2400 && now.cal === 2680);
  check('and the calorie target did not move with it',
    autoPlan(stored, now.cal, 190, NOW) === null);
}

/* ================= ONE GOAL DIRECTION, NOT TWO ================= */
{
  // food.js goalSign() and you.js goalDir() were the same decision written
  // twice. They are one rule now, and the thing to prove is that neither screen
  // changed its mind about a single account — so both OLD bodies are lifted out
  // of 9c1f0af and run against both NEW adapters over a grid.
  //
  // Bodies, not whole functions: each of the four reads `targets` from its
  // module scope, so the free variable becomes a parameter and nothing is
  // rewritten.
  const bodyOf = (text, head) => {
    const at = text.indexOf(head);
    if (at === -1) throw new Error('cannot find ' + head);
    let depth = 0, open = text.indexOf('{', at), end = -1;
    for (let j = open; j < text.length; j++) {
      if (text[j] === '{') depth++;
      else if (text[j] === '}' && --depth === 0) { end = j; break; }
    }
    return text.slice(open + 1, end);
  };
  const at40 = p => execFileSync('git', ['show', '9c1f0af:' + p],
                                 { cwd: SRC('.'), encoding: 'utf8', maxBuffer: 1 << 26 });

  // insights.js imports store.js, so the three pieces under test are lifted out
  // of it rather than the whole module being dragged in. They use nothing but
  // each other, which is the property that lets the native port copy them.
  const INS = readFileSync(SRC('insights.js'), 'utf8');
  const holdLine = /export const HOLD_RATE_LB = ([\d.]+);/.exec(INS);
  if (!holdLine) throw new Error('insights.js no longer exports HOLD_RATE_LB');
  // v47: rateVerdict also reads Coach's band. tools-check/rate-band.mjs is
  // where the band is proven; here it only has to be there for the lift.
  const bandLine = /export const RATE_BAND_LB = ([\d.]+);/.exec(INS);
  if (!bandLine) throw new Error('insights.js no longer exports RATE_BAND_LB');
  const gdFile = join(dir, 'goaldir.mjs');
  writeFileSync(gdFile,
    'export function goalDirection(targets, maintCal) {' + bodyOf(INS, '\nexport function goalDirection(') + '}\n' +
    'export const HOLD_RATE_LB = ' + holdLine[1] + ';\n' +
    'export const RATE_BAND_LB = ' + bandLine[1] + ';\n' +
    'export function rateVerdict(rateWk, dir) {' + bodyOf(INS, '\nexport function rateVerdict(') + '}\n');
  const { goalDirection, rateVerdict, HOLD_RATE_LB } = await import(pathToFileURL(gdFile).href);

  const oldSign = new Function('targets', 'maintCal', bodyOf(at40('food.js'), '\nfunction goalSign('));
  const oldDir  = new Function('targets', 'maint', bodyOf(at40('you.js'), '\nfunction goalDir('));
  const newSign = new Function('targets', 'maintCal', 'goalDirection',
                               bodyOf(readFileSync(SRC('food.js'), 'utf8'), '\nfunction goalSign('));
  const newDir  = new Function('targets', 'maint', 'goalDirection',
                               bodyOf(readFileSync(SRC('you.js'), 'utf8'), '\nfunction goalDir('));

  const RATES = [-5, -1, -0.5, 0, 0.5, 1, 5, NaN, null, undefined];
  const CALS  = [0, 1400, 1800, 2399, 2400, 2401, 2500, 2600, 3000];
  const MAINTS = [null, 500, 2400, 2500, 3000];
  const grid = [];
  RATES.forEach(rateWk => CALS.forEach(cal => MAINTS.forEach(mc => {
    grid.push([{ cal, auto: { on: true, rateWk } }, mc]);
    grid.push([{ cal }, mc]);                       // no auto block at all
  })));
  grid.push([{}, null], [{ auto: {} }, 2500], [{ cal: 2400, auto: null }, 2500]);

  // Fuel's `targets` is an object from the first line of the module and is
  // never null, which is why v40's goalSign could read targets.auto unguarded.
  // You's IS null on a skipped-onboarding account, so only that grid carries it.
  const signBad = grid.filter(([t, mc]) => oldSign(t, mc) !== newSign(t, mc, goalDirection));
  check('Fuel: goalSign answers exactly what it answered at v40, on all ' + grid.length + ' cases',
    signBad.length === 0, shape(signBad.slice(0, 2)));
  check('and the rule is now safe on a null targets, which v40’s Fuel copy threw on',
    goalDirection(null, 2500) === null &&
    (() => { try { oldSign(null, 2500); return false; } catch { return true; } })());

  // The You tab hands a maintInfo OBJECT around, so the grid is re-shaped the
  // way that screen really calls it.
  const asInfo = mc => (mc == null ? null : { cal: mc, pinned: false, source: 'pinned' });
  const youGrid = grid.concat([[null, 2500], [undefined, 2500], [null, null]]);
  const dirBad = youGrid.filter(([t, mc]) => oldDir(t, asInfo(mc)) !== newDir(t, asInfo(mc), goalDirection));
  check('You: goalDir answers exactly what it answered at v40, on all ' + youGrid.length + ' cases',
    dirBad.length === 0, shape(dirBad.slice(0, 2)));

  check('the two screens now read one rule — neither restates it',
    /const d = goalDirection\(targets, maintCal\);/.test(readFileSync(SRC('food.js'), 'utf8')) &&
    /return goalDirection\(targets, maint && maint\.cal\);/.test(readFileSync(SRC('you.js'), 'utf8')));
  // Since v47 the You tab's weekly-rate judges ask rateVerdict itself, so the
  // hold band lives in one function, not merely in one constant. (The Weight
  // card's 30-day arrow keeps half a pound over the MONTH, a different number
  // that happens to share the figure — rate-band.mjs covers it.)
  check('and the hold band is one number, not two',
    HOLD_RATE_LB === 0.5 &&
    readFileSync(SRC('you.js'), 'utf8').includes('const v = rateVerdict(n - p, dir);') &&
    readFileSync(SRC('you.js'), 'utf8').includes('const judgeRate = r => { const v = rateVerdict(r, dir);') &&
    !/HOLD_RATE_LB/.test(readFileSync(SRC('you.js'), 'utf8')));

  // null is not zero, and the Weight tab is the screen that needs the two apart.
  check('a stated cut is -1, a stated gain is +1',
    goalDirection({ cal: 2000, auto: { rateWk: -1 } }, 2500) === -1 &&
    goalDirection({ cal: 3000, auto: { rateWk: 1 } }, 2500) === 1);
  check('a target inside 100 kcal of maintenance is a HOLD, which is 0',
    goalDirection({ cal: 2450 }, 2500) === 0 && goalDirection({ cal: 2550 }, 2500) === 0);
  check('knowing nothing is null, not 0 — Fuel folds that to 0 itself',
    goalDirection({ cal: 2450 }, null) === null && goalDirection({}, 2500) === null &&
    goalDirection(null, 2500) === null);
  check('a maintenance of 0 is not a maintenance',
    goalDirection({ cal: 2450 }, 0) === null);

  /* ---- the colour ----
     Inside Coach's 1.5 lb band, which v47 put into rateVerdict. Past it the
     answer is null whichever way the rate points — rate-band.mjs proves that
     half — so these rates stay inside it. */
  check('a cut is green going down and amber going up — exactly v40’s colouring, inside the band',
    [-1.5, -0.4, 0].every(r => rateVerdict(r, -1) === 'good') &&
    [0.1, 1.5].every(r => rateVerdict(r, -1) === 'warn'));
  check('a GAIN is green going up — the bug: this was amber on every account gaining',
    [1.5, 0.4, 0].every(r => rateVerdict(r, 1) === 'good') &&
    [-0.1, -1.5].every(r => rateVerdict(r, 1) === 'warn'));
  check('holding is green inside half a pound a week, amber outside it',
    [0, 0.5, -0.5, 0.49].every(r => rateVerdict(r, 0) === 'good') &&
    [0.51, -0.51, 1.5].every(r => rateVerdict(r, 0) === 'warn'));
  check('and past the band, no colour at all, either way (v47)',
    [-2, 2, 3].every(r => [-1, 0, 1].every(d => rateVerdict(r, d) === null)));
  check('an unknown goal gets no colour at all, whatever the rate',
    [-2, 0, 2].every(r => rateVerdict(r, null) === null));
  check('and no rate gets no colour, whatever the goal',
    [null, undefined, NaN].every(r => [-1, 0, 1].every(d => rateVerdict(r, d) === null)));
  check('the Weight tab paints from the verdict and nothing else',
    /verdict === 'good' \? 'var\(--good\)' : verdict === 'warn' \? 'var\(--warn\)' : null/
      .test(readFileSync(SRC('weight.js'), 'utf8')));
  check('and the old down-is-good rule is gone from it',
    !/rate <= 0 \? 'var\(--good\)'/.test(readFileSync(SRC('weight.js'), 'utf8')));
}

/* ================= v57: THE NOTE UNDER THE BAR SAYS SOMETHING TRUE =================
   The bar's note fires for a gain when the target is at or under the hold
   band's top (calorieZones().gainFrom), and for a cut at or over its bottom.
   rack-v56 said "at or below your maintenance" either way, and Micah's Fuel
   tab on 25 Sep showed it under a target 250 OVER his maintenance. The words
   are food.js targetNote() now, pure, and every sentence it can print is held
   here to the numbers in it — parsed back out, never compared to a copy. */
{
  const FOOD = readFileSync(SRC('food.js'), 'utf8');
  const SET  = readFileSync(SRC('settings.js'), 'utf8');
  const loc = v => Math.round(v).toLocaleString();
  const num = s => Number(String(s).replace(/[^\d]/g, ''));
  const SAID = /^Your target, ([\d,.\s]+), sits (inside|below|above) your holding range \(maintenance ([\d,.\s]+) ± ([\d,.\s]+)\), so the calorie bar reads eating to it as (holding|cutting|bulking), not (bulking|cutting)\.$/;
  const READS = { maintain: 'holding', cut: 'cutting', gain: 'bulking' };
  // Every way the sentence can be false about (target, zones, goal), or null when it holds.
  const falsity = (note, t, z, g) => {
    const m = SAID.exec(note || '');
    if (!m) return 'not the sentence: ' + note;
    const [, T, where, M, B, reads, not] = m;
    if (num(T) !== Math.round(t) || num(M) !== z.maint || num(B) !== z.band) return 'numbers ' + [T, M, B].join(' / ');
    const lo = num(M) - num(B), hi = num(M) + num(B);
    const trueWhere = t < lo ? 'below' : t > hi ? 'above' : 'inside';
    if (where !== trueWhere) return '"' + where + '" of ' + t + ' against ' + lo + '–' + hi;
    if (reads !== READS[zoneOf(t, z)]) return 'reads as ' + reads + ', the bar paints ' + zoneOf(t, z);
    if (not !== (g > 0 ? 'bulking' : 'cutting')) return 'the goal is ' + g + ', said "not ' + not + '"';
    if (reads === not) return 'reads as the goal itself';
    return null;
  };

  // --- his case: rack-v57's band (tdee.js from git), the before ---
  const z57 = calorieZones57(3220);
  check('Micah’s maintenance, 3,220, at rack-v57: the band was ±250 — 8% is 257.6, rounded to a 25 and capped at 250 — so the hold band was 2,970 to 3,470, and his target, 3,470, sat on its top edge: holding',
    z57.band === 250 && z57.cutTop === 2970 && z57.gainFrom === 3470 && zoneOf(3470, z57) === 'maintain', shape(z57));
  const his = targetNote(3470, z57, 1);
  check('and the note fired, in v57’s words, true of v57’s numbers: "' + his + '"',
    his === 'Your target, ' + loc(3470) + ', sits inside your holding range (maintenance ' + loc(3220) + ' ± ' + loc(250) +
            '), so the calorie bar reads eating to it as holding, not bulking.' && falsity(his, 3470, z57, 1) === null, his);
  const V56 = execFileSync('git', ['show', '04e87cc:food.js'], { cwd: SRC('.'), encoding: 'utf8', maxBuffer: 1 << 26 });
  check('the control: rack-v56 said "at or below your measured maintenance" under the same condition — for him, of a target 250 over it',
    V56.includes("(g < 0 ? 'at or above' : 'at or below') + ' your '") && V56.includes("(g > 0 && targets.cal <= z.gainFrom)") &&
    3470 <= z57.gainFrom && 3470 > z57.maint);

  // --- his case, rack-v58: the band capped at 200, the after ---
  const z = calorieZones(3220);
  check('rack-v58: the same 257.6 is capped at 200, so the hold band is 3,020 to 3,420, and 3,470 is 50 past its top: the gain colour, bulking',
    z.band === 200 && z.cutTop === 3020 && z.gainFrom === 3420 && zoneOf(3470, z) === 'gain', shape(z));
  check('and the note under the bar does not fire — a gain goal with its target in the gain band, nothing to say — nor does Settings → Goal’s, the same function',
    targetNote(3470, z, 1) === null);
  check('Micah’s decision is the cap alone: the 8% and the rounding to 25 are rack-v57’s, and the floor of 150 — every maintenance from 500 to 6,000 gets the same band as rack-v57 where v57’s was 200 or less',
    (() => { for (let mc = 500; mc <= 6000; mc++) { const a = calorieZones57(mc).band, b = calorieZones(mc).band;
      if (b !== Math.min(a, 200)) return false; } return true; })());

  // --- every target, both goals, a grid of maintenances ---
  const MAINTS = [1200, 1875, 2000, 2400, 2656, 2657, 2968, 2969, 2970, 3000, 3220, 3225, 3500, 4200];
  const wrong = [], fired = { inside: 0, below: 0, above: 0 };
  let n = 0;
  MAINTS.forEach(mc => {
    const zz = calorieZones(mc);
    for (let t = mc - 700; t <= mc + 700; t += 5) [-1, 0, 1].forEach(g => {
      n++;
      const note = targetNote(t, zz, g);
      const was = (g < 0 && t >= zz.cutTop) || (g > 0 && t <= zz.gainFrom);
      if ((note !== null) !== was) { wrong.push(mc + '/' + t + '/' + g + ': fires ' + (note !== null) + ', the bar’s condition ' + was); return; }
      if (!note) return;
      const f = falsity(note, t, zz, g);
      if (f) wrong.push(mc + '/' + t + '/' + g + ': ' + f);
      else fired[SAID.exec(note)[2]]++;
    });
  });
  check('every target from 700 under to 700 over ' + MAINTS.length + ' maintenances, cut, hold and gain (' + n + '): the note fires exactly when v56’s did, and each sentence is true of its numbers — ' + shape(fired),
    !wrong.length && fired.inside > 0 && fired.below > 0 && fired.above > 0, wrong.slice(0, 3).join(' | '));
  check('no goal, no note — a hold has no wrong side, and nothing is known without zones',
    targetNote(3000, z, 0) === null && targetNote(3000, null, 1) === null && targetNote(NaN, z, 1) === null && targetNote(undefined, z, -1) === null);
  check('the target on the goal’s side says nothing: a gain at 3,430, a cut at 3,010 — ten past each edge',
    targetNote(3430, z, 1) === null && targetNote(3010, z, -1) === null);
  check('and a cut at the band’s bottom edge, 3,020, says so the same way: "' + targetNote(3020, z, -1) + '"',
    falsity(targetNote(3020, z, -1), 3020, z, -1) === null && /sits inside .* as holding, not cutting\.$/.test(targetNote(3020, z, -1)));

  // --- the band, in the numbers Micah decided from ---
  const BULK = { on: true, rateWk: 0.5, pPerLb: 1, fPerLb: 0.35, floor: 0 };
  check('Bulking is +0.5 lb a week (food.js GOAL_RATE) — 250 kcal a day at 3,500 a pound — and at his maintenance its own target is 3,470: rack-v57’s top edge exactly, 50 past rack-v58’s',
    /const GOAL_RATE = \{ cut: -1, hold: 0, gain: 0\.5 \};/.test(FOOD) && autoTargets(BULK, 3220, 200).cal === 3470 &&
    3470 === z57.gainFrom && 3470 - z.gainFrom === 50);
  check('and the Goal sheet’s by-hand target is the same arithmetic as autoTargets’: maintenance + rate × 500, to the nearest ten, never under the floor',
    FOOD.includes('next.cal = Math.max(floor, Math.round((mi.cal + rate * 500) / 10) * 10);'));

  /* Rack's three preset targets — Cutting, Maintaining and Bulking, food.js
     GOAL_RATE — at every whole maintenance from 1,500 to 4,500: a measured or
     setup number is a round ten, a typed one can be any. The floor is kept out
     of reach (no protein or fat, so it is the 100 g of carbs), since this asks
     what the band does to the presets; a floor that lifts a cut is below. */
  const PRESETS = [['Cutting', -1, 'cut'], ['Maintaining', 0, 'maintain'], ['Bulking', 0.5, 'gain']];
  const offColour = [], moved = { Cutting: [], Maintaining: [], Bulking: [] };
  for (let mc = 1500; mc <= 4500; mc++) PRESETS.forEach(([name, rateWk, own]) => {
    const t = autoTargets({ on: true, rateWk, pPerLb: 0, fPerLb: 0, floor: 0 }, mc, 200).cal;
    const was = zoneOf(t, calorieZones57(mc)), now = zoneOf(t, calorieZones(mc));
    if (now !== own) offColour.push(name + ' ' + mc + ': ' + t + ' ' + now);
    if (was !== now) moved[name].push([mc, was, now]);
  });
  check('rack-v58: at every maintenance from 1,500 to 4,500, each preset lands in its own colour — Cutting cut, Maintaining hold, Bulking gain',
    !offColour.length, offColour.slice(0, 4).join(' | '));
  check('Cutting and Maintaining change colour at no maintenance',
    !moved.Cutting.length && !moved.Maintaining.length, shape([moved.Cutting.slice(0, 2), moved.Maintaining.slice(0, 2)]));
  const bulkMoved = moved.Bulking.map(m => m[0]);
  const tens = bulkMoved.filter(mc => mc % 10 === 0);
  check('Bulking changes at ' + bulkMoved.length + ' of them, every one from holding to gaining: each maintenance from 2,969 up whose target, + 250 to the nearest ten, did not round past v57’s edge — ones digit 0 to 4',
    moved.Bulking.every(([, was, now]) => was === 'maintain' && now === 'gain') &&
    shape(bulkMoved) === shape(Array.from({ length: 4500 - 1500 + 1 }, (_, i) => 1500 + i).filter(mc => mc >= 2969 && mc % 10 <= 4)),
    shape(bulkMoved.slice(0, 6)));
  check('so for a measured maintenance (a round ten), Bulking read as holding at every one from 2,970 up — ' + tens.length + ' of them to 4,500 — and reads as gaining at all of them now',
    tens.length === (4500 - 2970) / 10 + 1 && tens[0] === 2970 && tens[tens.length - 1] === 4500);

  /* Any target, not only a preset's: the band moved only where rack-v57's was
     wider than 200 (225 from 2,657 to 2,968, 250 from 2,969 up), and there it
     moved exactly the targets more than 200 from maintenance and no further
     than v57's band — a hold that is a cut or a gain now. That is where a
     rate typed under Daily targets of 0.45 to 0.5 lb a week lands, and where a
     floor that lifts a cut up near maintenance can. Nothing else moves. */
  const other = [];
  for (let mc = 1500; mc <= 4500; mc++) {
    const a = calorieZones57(mc), b = calorieZones(mc);
    for (let d = -300; d <= 300; d++) {
      const was = zoneOf(mc + d, a), now = zoneOf(mc + d, b);
      const should = a.band > 200 && Math.abs(d) > 200 && Math.abs(d) <= a.band;
      if ((was !== now) !== should || (should && (was !== 'maintain' || now !== (d > 0 ? 'gain' : 'cut')))) other.push(mc + '/' + d + ': ' + was + ' → ' + now);
    }
  }
  check('any target from 300 under to 300 over every maintenance from 1,500 to 4,500: it changes colour exactly when it is more than 200 from maintenance and within v57’s band — which was wider than 200 only from 2,657 up — and then only from holding to its own side',
    !other.length, other.slice(0, 4).join(' | '));

  /* The Weight tab's rate colour and the You tab's insights do not read the
     band: they read insights.js HOLD_RATE_LB, 0.5 lb a week, and RATE_BAND_LB,
     a separate pair (rate-band.mjs). Moving the band moves neither. */
  const INS58 = readFileSync(SRC('insights.js'), 'utf8');
  check('the Weight tab and the You tab do not move: weight.js, you.js and insights.js name neither calorieZones nor zoneOf, insights.js is rack-v57’s byte for byte, and HOLD_RATE_LB is still 0.5',
    ['weight.js', 'you.js', 'insights.js'].every(f => !/calorieZones|zoneOf/.test(readFileSync(SRC(f), 'utf8'))) &&
    INS58 === execFileSync('git', ['show', V57 + ':insights.js'], { cwd: SRC('.'), encoding: 'utf8', maxBuffer: 1 << 26 }) &&
    /export const HOLD_RATE_LB = 0\.5;/.test(INS58));
  const bandReaders = readdirSync(SRC('.')).filter(f => f.endsWith('.js') && f !== 'tdee.js' && /calorieZones\(/.test(readFileSync(SRC(f), 'utf8')));
  check('and the band has one reader, food.js — the bar, its note, Reading the bar and Settings → Goal (goalFits, misfitNote) — so they move together: ' + bandReaders.join(', '),
    shape(bandReaders) === shape(['food.js']) && /goalFits\(goal0\)/.test(SET) && /misfitNote\(goal\)/.test(SET) &&
    (FOOD.match(/calorieZones\(mi\.cal\)/g) || []).length === 5);

  // --- one sentence, two screens ---
  check('the bar says it through targetNote(), and the old words are gone from food.js',
    /const note = targetNote\(targets\.cal, z, g\);/.test(FOOD) && !/holds rather than/.test(FOOD) && !/'at or below'/.test(FOOD));
  check('and Settings → Goal says the same sentence (misfitNote), offering Save only when it would move the target',
    /misfitNote\(goal\)/.test(SET) && /p\.changed \? ' Save to move it to '/.test(SET) && !/'at or below'|'at or above'/.test(SET));
}

/* ================= v58: READING THE BAR SAYS WHAT THE YELLOW COMES TO =================
   The sheet said a target in the yellow "holds your weight", and that inside
   the band "the scale will not move in any direction that matters" — at the
   edge of v57's 250, half a pound a week. Its two sentences about the yellow
   are food.js holdWords() and markWords() now, pure, and every sentence either
   can print is parsed back and held to the numbers: the band's edges and
   width, the target's distance from maintenance, and the weekly figure at
   3,500 kcal a pound or 7,716 a kilo, to the rounding the screen shows. */
{
  const FOOD = readFileSync(SRC('food.js'), 'utf8');
  const U = await load('units.mjs');
  const loc = v => Math.round(v).toLocaleString();
  const num = s => Number(String(s).replace(/[^\d]/g, ''));
  const z = calorieZones(3220), z57 = calorieZones57(3220);

  check('his yellow row: "' + holdWords(z, 'lb') + '"',
    holdWords(z, 'lb') === loc(3020) + ' to ' + loc(3420) + ' kcal: within 200 of maintenance either way, which Rack counts as holding. ' +
                           'Eating at its edge every day comes to about 0.4 lb a week, up or down.');
  check('and on a kilo account, the calories unconverted and the week in kilos: "…' + holdWords(z, 'kg').slice(-42) + '"',
    holdWords(z, 'kg').startsWith(loc(3020) + ' to ' + loc(3420) + ' kcal: within 200 ') && holdWords(z, 'kg').endsWith('comes to about 0.18 kg a week, up or down.'));
  check('his dashed mark, 3,470: "' + markWords(3470, z, 'lb') + '"',
    markWords(3470, z, 'lb') === 'it is in the red, so hitting it every day is a bulk.');
  const OLDFOOD = execFileSync('git', ['show', V57 + ':food.js'], { cwd: SRC('.'), encoding: 'utf8', maxBuffer: 1 << 26 });
  check('the before: at rack-v57’s band his target sat in the yellow, 250 over maintenance, and the sheet said eating to it "holds your weight"; those numbers would read now: "' + markWords(3470, z57, 'lb') + '"',
    OLDFOOD.includes("'it is in the yellow, so hitting it every day holds your weight.'") && OLDFOOD.includes('any direction that matters') &&
    markWords(3470, z57, 'lb') === 'it is in the yellow, 250 over maintenance, so Rack reads hitting it every day as holding — about 0.5 lb a week up.');

  const HOLDS = /^([\d,]+) to ([\d,]+) kcal: within ([\d,]+) of maintenance either way, which Rack counts as holding\. Eating at its edge every day comes to about ([\d.]+) (lb|kg) a week, up or down\.$/;
  const YELLOW = /^it is in the yellow, ([\d,]+) (over|under) maintenance, so Rack reads hitting it every day as holding(?: — about ([\d.]+) (lb|kg) a week (up|down))?\.$/;
  const near = (shown, kcal, u) => Math.abs(Number(shown) - kcal * 7 / U.kcalPerUnit(u)) <= (u === 'kg' ? 0.005 : 0.05) + 1e-6;
  const wrongHold = [], wrongMark = [], seen = { blue: 0, red: 0, at: 0, yellow: 0, silent: 0 };
  let nh = 0, nm = 0;
  // An odd step, so typed maintenances off the round tens are in it too.
  for (let mc = 1200; mc <= 4500; mc += 7) {
    const zz = calorieZones(mc);
    for (const u of ['lb', 'kg']) {
      nh++;
      const hs = holdWords(zz, u), h = HOLDS.exec(hs);
      if (!h || num(h[1]) !== zz.cutTop || num(h[2]) !== zz.gainFrom || num(h[3]) !== zz.band || h[5] !== u ||
          !near(h[4], zz.band, u)) wrongHold.push(mc + ' ' + u + ': ' + hs);
      for (let t = mc - 400; t <= mc + 400; t += 5) {
        nm++;
        const s = markWords(t, zz, u), zone = zoneOf(t, zz), d = Math.round(t - mc);
        const bad = () => wrongMark.push(mc + '/' + t + ' ' + u + ': ' + s);
        if (zone === 'cut')  { if (s === 'it is in the blue, so hitting it every day is a cut.') seen.blue++; else bad(); continue; }
        if (zone === 'gain') { if (s === 'it is in the red, so hitting it every day is a bulk.') seen.red++; else bad(); continue; }
        if (d === 0) { if (s === 'it is in the yellow, at maintenance itself, so hitting it every day holds your weight.') seen.at++; else bad(); continue; }
        const m = YELLOW.exec(s);
        if (!m || num(m[1]) !== Math.abs(d) || m[2] !== (d > 0 ? 'over' : 'under')) { bad(); continue; }
        if (m[3] === undefined) { if (U.fmtRate(Math.abs(d) * 7 / 3500, u) === '0') seen.silent++; else bad(); continue; }
        if (m[4] === u && m[5] === (d > 0 ? 'up' : 'down') && near(m[3], Math.abs(d), u)) seen.yellow++; else bad();
      }
    }
  }
  check('every yellow row, ' + nh + ' of them (maintenance 1,200 to 4,500, pounds and kilos): its edges and width are the band’s, and its weekly figure is the width at the unit’s own kcal, to the rounding shown',
    !wrongHold.length, wrongHold.slice(0, 3).join(' | '));
  check('every dashed mark, ' + nm + ' of them (400 either side): blue and red as the bar paints them, and in the yellow the distance, its side, and the week it comes to — ' + shape(seen),
    !wrongMark.length && Object.values(seen).every(v => v > 0), wrongMark.slice(0, 3).join(' | '));
  check('the sheet says them — the yellow row is holdWords(), the dashed mark markWords(), both in the account’s unit — and the old words are gone from food.js',
    FOOD.includes("row('hold', 'Yellow — hold', holdWords(z, wu()));") && FOOD.includes('markWords(targets.cal, z, wu())') &&
    !FOOD.includes('any direction that matters') && !FOOD.includes("'it is in the yellow, so hitting it every day holds your weight.'"));
}

/* ---------- report ---------- */

console.log('\nmaintenance — which number the app quotes\n');
console.log(results.join('\n'));
console.log('\n' + pass + ' passed, ' + fail + ' failed\n');
process.exit(fail ? 1 : 0);
