#!/usr/bin/env node
//
// Verifier for which maintenance number the app quotes.
//
//   node tools-check/maintenance.mjs
//
// The precedence used to be hand-copied into Fuel, You and Weight. It is one
// function now — effectiveMaint() in tdee.js — and this drives the REAL one,
// along with the two pure cores in food.js that decide what Save writes
// (maintPatch) and when auto targets are allowed to move (autoPlan). No copy of
// any of that logic lives in here; a verifier with its own copy stops being
// true the moment the file it checks changes.
//
// What it proves:
//   - the four-way precedence: pinned, measured, setup, and "we don't know";
//   - an ABSENT maintSrc reads as pinned, so none of the eight accounts that
//     predate the key has its number moved by this ship;
//   - a setup number expires the moment there is a measured estimate, and
//     comes BACK if that estimate is later lost — nothing is rewritten;
//   - opening Daily targets and saving it untouched leaves a setup number a
//     setup number, which is the bug that would otherwise turn every guess
//     into a pin the first time somebody edited their protein;
//   - typing a number pins it, blanking it clears both keys;
//   - and a setup number expiring cannot move the calorie target outside the
//     weekly gate, however far maintenance jumps.

import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const SRC  = p => join(HERE, '..', p);

/* ---------- the fake browser ----------
   store.js touches four globals at load and food.js touches none until it is
   called. Nothing below renders, so this is the whole of it. */

const cells = new Map();
globalThis.localStorage = {
  getItem: k => (cells.has(k) ? cells.get(k) : null),
  setItem: (k, v) => cells.set(k, String(v)),
  removeItem: k => cells.delete(k),
  key: i => Array.from(cells.keys())[i] ?? null,
  get length() { return cells.size; }
};
globalThis.window = { addEventListener() {} };
globalThis.document = { body: null, getElementById: () => null, createElement: () => ({ style: {} }) };
try {
  Object.defineProperty(globalThis, 'navigator', {
    value: { onLine: true }, configurable: true, writable: true
  });
} catch { /* Node may own it; nothing here reads it */ }

/* ---------- staging ----------

   The modules whose real code is under test are copied as-is with their
   relative imports repointed at each other. Everything else any of them
   imports — the Firebase SDK, the estimator, Water, Recall, usage counters —
   becomes one generated stub, because none of it is reachable from a pure
   function and loading it would drag the whole app into a unit test.

   The stub's exports are generated by reading the import statements rather
   than by listing names here, so a new import in food.js does not silently
   break this file with "does not provide an export named". */

const REAL = ['store.js', 'ui.js', 'units.js', 'weightmodel.js', 'tdee.js', 'food.js'];
const IMPORT_RE = /\bfrom\s+(['"])([^'"]+)\1/g;
const NAMED_RE  = /\bimport\s*\{([^}]*)\}\s*from\s+(['"])([^'"]+)\2/g;

const sources = new Map(REAL.map(f => [f, readFileSync(SRC(f), 'utf8')]));
const stubbed = new Set();

for (const text of sources.values()) {
  let m;
  NAMED_RE.lastIndex = 0;
  while ((m = NAMED_RE.exec(text))) {
    const spec = m[3];
    const base = spec.startsWith('./') ? spec.slice(2) : null;
    if (base && REAL.includes(base)) continue;
    for (const raw of m[1].split(',')) {
      // `forget as recallForget` — the stub has to export `forget`, the name on
      // the left. Taking the local binding instead is how this fails with
      // "does not provide an export named".
      const name = raw.trim().split(/\s+as\s+/)[0].trim();
      if (name) stubbed.add(name);
    }
  }
}

// Every stubbed name is a callable that returns undefined. That is enough:
// store.js calls initializeApp/getAuth/getDatabase at load and nothing else in
// here reaches a stub, so a stub that is ever actually USED by a test would
// show up as a wrong answer rather than as a pass.
const stub = Array.from(stubbed)
  .map(n => `export function ${n}() {}`)
  .join('\n') + '\n';

const dir = mkdtempSync(join(tmpdir(), 'rack-maint-'));
writeFileSync(join(dir, 'stub.mjs'), stub);
for (const [file, text] of sources) {
  writeFileSync(join(dir, file.replace(/\.js$/, '.mjs')),
    text.replace(IMPORT_RE, (whole, q, spec) => {
      const base = spec.startsWith('./') ? spec.slice(2) : null;
      return base && REAL.includes(base)
        ? `from './${base.replace(/\.js$/, '.mjs')}'`
        : `from './stub.mjs'`;
    }));
}

const load = f => import(pathToFileURL(join(dir, f)).href);
const { effectiveMaint, autoTargets } = await load('tdee.mjs');
const { maintPatch, autoPlan } = await load('food.mjs');

/* ---------- harness ---------- */

let pass = 0, fail = 0;
const results = [];
function check(name, ok, detail) {
  if (ok) { pass++; results.push('  ok   ' + name); }
  else    { fail++; results.push('  FAIL ' + name + (detail ? '  — ' + detail : '')); }
}
const shape = v => JSON.stringify(v);

// maintenance()'s return, narrowed to the one field effectiveMaint reads.
const EST   = tdee => ({ tdee, avgIntake: 2600, days: 12, rateWk: -0.4, need: [] });
const NOEST = { tdee: null, avgIntake: null, days: 3, rateWk: null, need: ['4 more days of food logging'] };

/* ---------- 1. the four-way precedence ---------- */

{
  const pinned = effectiveMaint({ maint: 2400, maintSrc: 'pinned' }, EST(2680));
  check('pinned beats a measured estimate',
    pinned && pinned.cal === 2400 && pinned.source === 'pinned' && pinned.auto === false,
    shape(pinned));

  const measured = effectiveMaint({ maint: 2400, maintSrc: 'setup' }, EST(2680));
  check('a setup number loses to a measured estimate',
    measured && measured.cal === 2680 && measured.source === 'measured' && measured.auto === true,
    shape(measured));

  const setup = effectiveMaint({ maint: 2400, maintSrc: 'setup' }, NOEST);
  check('a setup number is used while there is no estimate',
    setup && setup.cal === 2400 && setup.source === 'setup' && setup.auto === false,
    shape(setup));

  check('nothing stored and nothing measured is null, not a guess',
    effectiveMaint({ maint: null }, NOEST) === null);
  check('no targets node at all is null',
    effectiveMaint(null, null) === null && effectiveMaint(undefined, undefined) === null);
}

/* ---------- 2. the eight existing accounts do not move ----------
   No stored account has maintSrc. If absent read as "setup", every one of them
   would silently start quoting a different maintenance number on the morning
   this ships — including anyone who typed theirs on purpose. */

{
  const a = effectiveMaint({ maint: 2400 }, EST(2680));
  check('absent maintSrc reads as pinned, even with an estimate available',
    a && a.cal === 2400 && a.source === 'pinned', shape(a));

  const b = effectiveMaint({ maint: 2400, maintSrc: undefined }, EST(2680));
  check('an explicitly undefined maintSrc reads as pinned',
    b && b.source === 'pinned', shape(b));

  const c = effectiveMaint({ maint: 2400, maintSrc: null }, EST(2680));
  check('a null maintSrc reads as pinned', c && c.source === 'pinned', shape(c));

  // A value nobody wrote is not a licence to move somebody's number either.
  const d = effectiveMaint({ maint: 2400, maintSrc: 'SETUP' }, EST(2680));
  check('an unrecognised maintSrc reads as pinned, never as setup',
    d && d.source === 'pinned', shape(d));
}

/* ---------- 3. expiry, and coming back ----------
   Expiry is a read-side decision and nothing is rewritten, which is what makes
   it reversible: the same stored record answers differently as the model gains
   and loses its estimate. */

{
  const stored = { maint: 2400, maintSrc: 'setup' };
  check('setup + no estimate -> setup',
    effectiveMaint(stored, NOEST).source === 'setup');
  check('setup + estimate -> measured',
    effectiveMaint(stored, EST(2680)).source === 'measured');
  check('estimate lost -> back to setup, from the same stored record',
    effectiveMaint(stored, NOEST).cal === 2400 &&
    effectiveMaint(stored, NOEST).source === 'setup');
  check('the stored record was not mutated by any of that',
    shape(stored) === shape({ maint: 2400, maintSrc: 'setup' }), shape(stored));

  // The model's own sufficiency bar, not a second one invented here.
  check('a null tdee is not an estimate',
    effectiveMaint(stored, { tdee: null }).source === 'setup');
  check('a zero tdee is not a maintenance number',
    effectiveMaint(stored, { tdee: 0 }).source === 'setup');
  check('a NaN tdee is not a maintenance number',
    effectiveMaint(stored, { tdee: NaN }).source === 'setup');
  check('with no stored number and no usable estimate the answer is null',
    effectiveMaint({ maint: 0 }, { tdee: 0 }) === null);
}

/* ---------- 4. the Daily-targets sheet ----------
   The box is prefilled with a number somebody CHOSE and nothing else. These
   drive maintPatch() with the same (box, whatItOpenedWith, stored) the sheet
   passes it. */

{
  // THE ONE THAT MATTERS. A setup account opens the sheet to change its
  // protein; the maintenance box is empty because the setup number is a
  // placeholder, and Save must not touch either key.
  const stored = { maint: 2400, maintSrc: 'setup', cal: 2100, p: 190, f: 70 };
  const r = maintPatch('', '', stored);
  check('sheet saved untouched: a setup number stays a setup number',
    r.maint === 2400 && r.maintSrc === 'setup' && r.changed === false, shape(r));
  check('sheet saved untouched: the number in force is still the setup one',
    effectiveMaint({ ...stored, ...r }, NOEST).source === 'setup');
  check('sheet saved untouched: and still expires when the estimate arrives',
    effectiveMaint({ ...stored, ...r }, EST(2680)).source === 'measured');
}

{
  // The same for the accounts with no maintSrc: the box opens holding their
  // number, and an untouched Save must not stamp it 'pinned' either — that
  // would answer the one-time question on their behalf.
  const stored = { maint: 2400, cal: 2100 };
  const r = maintPatch('2400', '2400', stored);
  check('sheet saved untouched: an absent maintSrc stays absent',
    r.maint === 2400 && r.maintSrc === null && r.changed === false, shape(r));
}

{
  const stored = { maint: 2400, maintSrc: 'pinned' };
  const r = maintPatch('2400', '2400', stored);
  check('sheet saved untouched: a pinned number stays pinned',
    r.maint === 2400 && r.maintSrc === 'pinned' && r.changed === false, shape(r));
}

{
  const stored = { maint: 2400, maintSrc: 'setup' };
  const r = maintPatch('2550', '', stored);
  check('typing a number over a setup placeholder pins it',
    r.maint === 2550 && r.maintSrc === 'pinned' && r.changed === true, shape(r));
  check('a pinned number then beats the estimate',
    effectiveMaint({ ...stored, ...r }, EST(2680)).cal === 2550);
}

{
  const stored = { maint: 2400, maintSrc: 'pinned' };
  const r = maintPatch('', '2400', stored);
  check('typed then blanked: both keys cleared',
    r.maint === null && r.maintSrc === null && r.changed === true, shape(r));
  check('typed then blanked: the estimate takes over',
    effectiveMaint({ ...stored, ...r }, EST(2680)).source === 'measured');
  check('typed then blanked with no estimate: we genuinely do not know',
    effectiveMaint({ ...stored, ...r }, NOEST) === null);
}

{
  const stored = { maint: 2400 };
  check('editing an absent-maintSrc number pins it',
    shape(maintPatch('2500', '2400', stored)) === shape({ maint: 2500, maintSrc: 'pinned', changed: true }));
  check('junk in the box clears, the way parseInt always made it',
    shape(maintPatch('abc', '2400', stored)) === shape({ maint: null, maintSrc: null, changed: true }));
  check('zero clears rather than pinning a zero',
    shape(maintPatch('0', '2400', stored)) === shape({ maint: null, maintSrc: null, changed: true }));
  check('whitespace either side is not a change',
    maintPatch(' 2400 ', '2400', stored).changed === false);
  check('a sheet opened on an empty box and left empty writes nothing new',
    shape(maintPatch('', '', { maint: null })) === shape({ maint: null, maintSrc: null, changed: false }));
}

/* ---------- 5. auto targets and the weekly gate ----------
   A setup number expiring can move maintenance by hundreds of kcal in one
   render. The gate is what keeps the calorie target from following it there
   and then, and this is the proof that the gate is still in the path. */

const DAY = 864e5;
const NOW = 1_758_000_000_000;           // fixed: autoPlan takes its clock as an argument
const GOAL = { on: true, rateWk: -1, pPerLb: 1, fPerLb: 0.35, floor: 0, lastAdj: 0 };

{
  const before = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: NOW - 2 * DAY } };
  const jump = autoPlan(before, 2680, 190, NOW);
  check('maintenance jumping does not move the target two days after the last move',
    jump === null, shape(jump));

  const due = autoPlan({ ...before, auto: { ...GOAL, lastAdj: NOW - 8 * DAY } }, 2680, 190, NOW);
  check('the same jump moves it a week later', due !== null && due.cal > before.cal, shape(due));
  check('and moves it by at most one step',
    due && due.cal - before.cal <= 100, shape(due));
  check('and stamps the clock it was given, not one of its own',
    due && due.lastAdj === NOW, shape(due));
}

{
  // The boundary itself, in both directions.
  const at = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: NOW - 7 * DAY } };
  check('exactly seven days is due', autoPlan(at, 2680, 190, NOW) !== null);
  const just = { ...at, auto: { ...GOAL, lastAdj: NOW - 7 * DAY + 1000 } };
  check('a second short of seven days is not', autoPlan(just, 2680, 190, NOW) === null);
}

{
  const off = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, on: false, lastAdj: 0 } };
  check('auto targets switched off never move', autoPlan(off, 2680, 190, NOW) === null);
  check('no maintenance number, no move',
    autoPlan({ cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: 0 } }, 0, 190, NOW) === null);
  check('no trend weight, no move',
    autoPlan({ cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: 0 } }, 2680, 0, NOW) === null);
}

{
  // A never-adjusted account (lastAdj 0) is allowed to move, which is how the
  // first adjustment ever happens — the gate is "not recently", not "never".
  const fresh = { cal: 1900, p: 190, f: 67, auto: { ...GOAL, lastAdj: 0 } };
  check('an account that has never adjusted is due', autoPlan(fresh, 2680, 190, NOW) !== null);

  // …and a move too small to be worth making is still not made.
  const settled = autoTargets(GOAL, 2680, 190);
  const sameish = { cal: settled.cal, p: settled.p, f: settled.f, auto: { ...GOAL, lastAdj: 0 } };
  check('a target already where the maths puts it does not churn',
    autoPlan(sameish, 2680, 190, NOW) === null, shape(autoPlan(sameish, 2680, 190, NOW)));
}

{
  // End to end: the day a setup number expires, nothing moves on render.
  const stored = { maint: 2400, maintSrc: 'setup', cal: 1900, p: 190, f: 67,
                   auto: { ...GOAL, lastAdj: NOW - DAY } };
  const was = effectiveMaint(stored, NOEST);
  const now = effectiveMaint(stored, EST(2680));
  check('the number quoted really did jump on expiry',
    was.cal === 2400 && now.cal === 2680);
  check('and the calorie target did not move with it',
    autoPlan(stored, now.cal, 190, NOW) === null);
}

/* ---------- report ---------- */

console.log('\nmaintenance — which number the app quotes\n');
console.log(results.join('\n'));
console.log('\n' + pass + ' passed, ' + fail + ' failed\n');
process.exit(fail ? 1 : 0);
