// 08a-spec.mjs — Track 8a's hand-written provenance facts, one object per candidate photo.
// 08a-build.mjs adds the file facts (bytes, sha256, dims, retrieved) measured from the downloaded originals.
// Every fact here comes from the item page / API record cited in source_url, except fields marked (inference).
const LOCB = 'No known restrictions on publication. For more information, see George Grantham Bain Collection - Rights and Restrictions Information https://www.loc.gov/rr/print/res/274_bain.html';
const LOCN = 'No known restrictions on publication. For more information, see National Photo Company Collection - Rights and Restrictions Information https://www.loc.gov/rr/print/res/275_npco.html';
const NKR = 'No known restrictions on publication.';
const DESB = {
  source_institution: 'Internet Archive (scan contributed by University of Michigan Library)',
  source_url: 'https://archive.org/details/4908148.0001.001.umich.edu',
  book: 'Edmond Desbonnet, Les rois de la force : histoire de tous les hommes forts depuis les temps anciens jusqu\'à nos jours (Paris: Librairie Berger-Levrault, 1911)',
  rights_statement_verbatim: 'None displayed. The Internet Archive item carries no rights, licenseurl or possible-copyright-status field (metadata API, retrieved 2026-09-26); collections: michigan_books, americana.',
  pd_basis_us: 'Published in Paris in 1911, before 1931: US copyright term expired (published before 1931).',
  pd_basis_worldwide: 'Book author Edmond Desbonnet died 1953 (life+70 ended 31 Dec 2023). The halftone photographs are uncredited in the book (anonymous): EU/UK anonymous-work term is 70 years from publication (1911+70 = 1981).',
  creator_died: 'anonymous (uncredited in the book); book author Edmond Desbonnet 1867–1953',
};
export const specs = [
  {
    file: 'sandwina-three-men.tif', tier: 'A', confidence: 'high',
    title: 'Katie Sandwina, the Lady Hercules (holding up three men)',
    subject: 'Strongwoman Katie Sandwina in a stage leotard and boots, lifting three men in evening dress; printed caption "The Lady Hercules Katie Sandwina" top left.',
    creator: 'Bain News Service (publisher); the underlying publicity photograph is uncredited', creator_died: 'Bain News Service founder George Grantham Bain died 1944; original photographer anonymous',
    created: 'c. 1911–1913 (inference: Bain negative LC-B2-1305 sits beside portraits of Sen. L.Y. Sherman and Judge Lydia B. Tague; LoC records "[no date recorded on caption card]")',
    first_published: { year: 'c. 1911–1913 (inference)', venue: 'Bain News Service photo distribution to subscribing newspapers (LoC: "photographs Bain produced and gathered for distribution through his news service")' },
    source_institution: 'Library of Congress, Prints & Photographs Division (George Grantham Bain Collection)', source_url: 'https://www.loc.gov/item/2014686831/', source_id: 'LC-DIG-ggbain-06839 (call no. LC-B2- 1305-7)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/ggbain/06800/06839u.tif',
    rights_statement_verbatim: LOCB,
    pd_basis_us: 'Distributed (published) by Bain News Service before 1931; LoC: no known restrictions on publication.',
    pd_basis_worldwide: 'Anonymous photograph, made public c.1911–1913: EU/UK anonymous term (70 years from making available) expired by 1983; Bain himself died 1944 (life+70 ended 2014).',
    clothing_check: 'PASS — sleeveless stage leotard (bodice + briefs) over tights, lace-up boots; men fully dressed.',
    credit_line: 'Library of Congress, Prints & Photographs Division, LC-DIG-ggbain-06839',
    focal: { x: 0.565, y: 0.31 }, crop_hint: { x0: 0.10, y0: 0.03, x1: 0.93, y1: 0.95 },
    notes: 'Portrait frame; wide crop keeps the four faces in a band y≈0.20–0.40. Negative is a copy of a printed card: printed caption in frame (top left), glass-plate spots at edges.',
  },
  {
    file: 'sandwina-lady-hercules.tif', tier: 'A', confidence: 'high',
    title: 'Katie Sandwina, the lady Hercules',
    subject: 'Katie Sandwina posing in a leotard and boots beside a jardinière, three men in evening dress to the left; printed caption at bottom.',
    creator: 'Bain News Service (publisher); underlying publicity photograph uncredited', creator_died: 'Bain died 1944; original photographer anonymous',
    created: 'c. 1911–1913 (inference, same negative run LC-B2-1305 as above)',
    first_published: { year: 'c. 1911–1913 (inference)', venue: 'Bain News Service distribution' },
    source_institution: 'Library of Congress, Prints & Photographs Division (George Grantham Bain Collection)', source_url: 'https://www.loc.gov/item/2014686832/', source_id: 'LC-DIG-ggbain-06840 (call no. LC-B2- 1305-9)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/ggbain/06800/06840u.tif',
    rights_statement_verbatim: LOCB,
    pd_basis_us: 'Distributed by Bain News Service before 1931; LoC: no known restrictions on publication.',
    pd_basis_worldwide: 'Anonymous, made public c.1911–1913 (70-year anonymous term expired); Bain d.1944.',
    clothing_check: 'PASS — corseted stage leotard with tights and lace-up boots.',
    credit_line: 'Library of Congress, Prints & Photographs Division, LC-DIG-ggbain-06840',
    focal: { x: 0.75, y: 0.20 }, crop_hint: { x0: 0.11, y0: 0.09, x1: 0.96, y1: 0.86 },
    notes: 'Printed caption "A Combination of female Strength, Form & Beauty" at bottom — crop above y≈0.86. Torn print edges.',
  },
  {
    file: 'hackenschmidt-bain-1908.tif', tier: 'A', confidence: 'high',
    title: 'Geo. Hacken Schmidt [i.e. George Hackenschmidt]',
    subject: 'Wrestler and strongman George Hackenschmidt, half-length, in overcoat, collar, tie and bowler-style hat, outdoors.',
    creator: 'Bain News Service (publisher); photographer unrecorded', creator_died: 'Bain died 1944; photographer anonymous',
    created: 'c. 1908 (inference: negative run LC-B2-125 also holds portraits of Portuguese ministers Campos Henriques and Augusto de Castilho, in office 1908–09; LoC records "[no date recorded on caption card]")',
    first_published: { year: 'c. 1908 (inference)', venue: 'Bain News Service distribution' },
    source_institution: 'Library of Congress, Prints & Photographs Division (George Grantham Bain Collection)', source_url: 'https://www.loc.gov/item/2014680730/', source_id: 'LC-DIG-ggbain-00734 (call no. LC-B2- 125-6)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/ggbain/00700/00734u.tif',
    rights_statement_verbatim: LOCB,
    pd_basis_us: 'Distributed by Bain News Service before 1931; LoC: no known restrictions on publication.',
    pd_basis_worldwide: 'Anonymous press photograph c.1908 (70-year anonymous term expired); Bain d.1944.',
    clothing_check: 'PASS — street clothes (overcoat, shirt, tie, hat).',
    credit_line: 'Library of Congress, Prints & Photographs Division, LC-DIG-ggbain-00734',
    focal: { x: 0.47, y: 0.46 }, crop_hint: { x0: 0.03, y0: 0.12, x1: 0.96, y1: 0.95 },
    notes: 'Landscape frame, face centred: the easiest wide crop in the set. Scratched title "GEO. HACKENSCHMIDT 125-6" along the top edge — crop below y≈0.12. Subject died 1968: never imply endorsement.',
  },
  {
    file: 'joe-rogers-gym.tif', tier: 'A', confidence: 'high',
    title: 'Joe Rogers, "The America Apollo" [in gymnasium]',
    subject: 'Wrestler Joe Rogers standing in a gymnasium in singlet, belt, tights with knee pads and boots; rings and athletes blurred behind.',
    creator: 'Bain News Service (publisher); photographer unrecorded', creator_died: 'Bain died 1944; photographer anonymous',
    created: 'c. 1908–1909 (inference: negative run LC-B2-494 also holds wrestler Yussif Mahmout, in the US 1908–09, and "Mrs. G.B. McClellan decorating firemen", NYC mayoralty 1904–09)',
    first_published: { year: 'c. 1908–1909 (inference)', venue: 'Bain News Service distribution' },
    source_institution: 'Library of Congress, Prints & Photographs Division (George Grantham Bain Collection)', source_url: 'https://www.loc.gov/item/2014682390/', source_id: 'LC-DIG-ggbain-02395 (call no. LC-B2- 494-5)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/ggbain/02300/02395u.tif',
    rights_statement_verbatim: LOCB,
    pd_basis_us: 'Distributed by Bain News Service before 1931; LoC: no known restrictions on publication.',
    pd_basis_worldwide: 'Anonymous press photograph c.1908–09 (70-year anonymous term expired); Bain d.1944.',
    clothing_check: 'PASS — sleeveless singlet, waist belt, full-length tights with knee pads, boots.',
    credit_line: 'Library of Congress, Prints & Photographs Division, LC-DIG-ggbain-02395',
    focal: { x: 0.51, y: 0.30 }, crop_hint: { x0: 0.04, y0: 0.12, x1: 0.97, y1: 0.95 },
    notes: 'Best "gym + athlete" frame in the set: landscape, subject centred, real gymnasium behind. Scratched title across top edge — crop below y≈0.12.',
  },
  {
    file: 'sandow-falk-leotard-1894.tif', tier: 'A', confidence: 'high',
    title: '[Eugen Sandow, full-length portrait, standing, leaning on column, facing left, wearing wrestling leotard, Roman sandles, and six pointed star pendant]',
    subject: 'Eugen Sandow in a wrestling leotard, belt and sandals, leaning on a column; studio cabinet card.',
    creator: 'B. J. (Benjamin J.) Falk, photographer', creator_died: '1925',
    created: 'c1894', first_published: { year: '1894', venue: 'Cabinet photograph copyrighted and sold by B.J. Falk, 13 & 15 West 24th St., New York (U.S. Copyright Office 17486Z)' },
    source_institution: 'Library of Congress, Prints & Photographs Division (via Wikimedia Commons route, see rights)', source_url: 'https://www.loc.gov/item/91480334/', source_id: 'LC-USZ62-104521 (digital file cph.3c04521; LOT 12388)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/cph/3c00000/3c04000/3c04500/3c04521u.tif',
    rights_statement_verbatim: 'LoC item record carries no rights advisory (empty in the item JSON). Wikimedia Commons copy of this exact LoC file (https://commons.wikimedia.org/wiki/File:Eugene_Sandow,_full-length_portrait,_standing,_leaning_on_column,_facing_left,_wearing_wrestling_leotard,_Roman_sandles,_and_six_pointed_star_pendant_LCCN91480334.tif) is tagged {{PD-old-70-1923}} (renders PD-US-expired + PD-old-70-expired).',
    pd_basis_us: 'Published (copyright-registered) 1894, before 1931.',
    pd_basis_worldwide: 'Photographer B.J. Falk died 1925: life+70 ended 1995.',
    clothing_check: 'PASS — one-piece wrestling leotard (low scoop neck), belt, laced sandals; no nudity.',
    credit_line: 'B.J. Falk, 1894. Library of Congress, Prints & Photographs Division, LC-USZ62-104521',
    focal: { x: 0.53, y: 0.20 }, crop_hint: { x0: 0.19, y0: 0.04, x1: 0.83, y1: 0.86 },
    notes: 'Passes §14 on the Commons route (both tags, traced to this LoC file); it fails the LoC-only route because LoC shows no rights advisory. Bytes fetched from that Commons copy, proven identical to the LoC master (download_url.byte_identity). Copyright-office number "17486Z" inked lower right and a stamp on the thigh; card text "SANDOW / Falk" below y≈0.86. 3:1 crop gives 2053 px.',
  },
  {
    file: 'sandow-falk-fur-1895.tif', tier: 'A', confidence: 'medium',
    title: 'Sandow / Falk.',
    subject: 'Eugen Sandow standing on a fur-draped plinth in a fitted one-shoulder leopard-skin costume with belt and laced sandals.',
    creator: 'B. J. (Benjamin J.) Falk, photographer', creator_died: '1925',
    created: 'c1895 Oct. 16', first_published: { year: '1895', venue: 'Panel card, N.Y.: Falk, 13 & 15 West 24th St.; U.S. Copyright Office 48694-aa; stamped "Copyright 1895 by B.J. Falk N.Y."' },
    source_institution: 'Library of Congress, Prints & Photographs Division', source_url: 'https://www.loc.gov/item/2007681316/', source_id: 'LC-USZ62-22030 (digital file cph.3a23125; LOT 12388)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/cph/3a20000/3a23000/3a23100/3a23125u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'Published and registered 1895, before 1931.',
    pd_basis_worldwide: 'Falk died 1925: life+70 ended 1995.',
    clothing_check: 'PASS (borderline, Micah to eye) — a fitted, belted one-shoulder fur costume worn as a garment, not a drape over nudity; legs bare above the sandals.',
    credit_line: 'B.J. Falk, 1895. Library of Congress, Prints & Photographs Division, LC-USZ62-22030',
    focal: { x: 0.51, y: 0.16 }, crop_hint: { x0: 0.03, y0: 0.01, x1: 0.97, y1: 0.90 },
    notes: 'Low-resolution copy-negative scan (see dims). Card text "SANDOW / Falk" and copyright stamps at bottom.',
  },
  {
    file: 'sandow-falk-no43-1895.tif', tier: 'A', confidence: 'medium',
    title: 'Eugen Sandow, 1867-1925',
    subject: 'Eugen Sandow, three-quarter length, in the same belted one-shoulder fur costume, looking up; "Copyright 1895 by B.J. Falk" lower right.',
    creator: 'B. J. Falk (record: "Photoprint copyrighted by B.J. Falk")', creator_died: '1925',
    created: 'c1895', first_published: { year: '1895', venue: 'Photoprint copyrighted by B.J. Falk, New York (No. 43)' },
    source_institution: 'Library of Congress, Prints & Photographs Division', source_url: 'https://www.loc.gov/item/2002697564/', source_id: 'LC-USZ62-75414 (digital file cph.3b22615; BIOG FILE - Sandow)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/cph/3b20000/3b22000/3b22600/3b22615u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'Published and copyrighted 1895, before 1931.',
    pd_basis_worldwide: 'Falk died 1925: life+70 ended 1995.',
    clothing_check: 'PASS (borderline, Micah to eye) — same belted fur costume; bare arm and shoulder.',
    credit_line: 'B.J. Falk, 1895. Library of Congress, Prints & Photographs Division, LC-USZ62-75414',
    focal: { x: 0.56, y: 0.20 }, crop_hint: { x0: 0.0, y0: 0.0, x1: 1.0, y1: 0.93 },
    notes: 'Tight portrait — the strongest face-and-shoulders crop of Sandow that passes the clothing rule. Low-resolution copy negative (1036 px wide: @2x only). Bytes fetched from the Commons copy (tagged PD-old-70-1923) because tile.loc.gov stalled; proven identical to the LoC master (see download_url.byte_identity).',
  },
  {
    file: 'gym-naval-academy.tif', tier: 'A', confidence: 'high',
    title: '[Gymnasium interior, U.S. Naval Academy]',
    subject: 'Empty gymnasium under a timber truss roof: climbing ropes, pommel horse, mats, rings, gallery, dumbbell racks along the far wall.',
    creator: 'Detroit Publishing Co. (publisher); photographer unrecorded', creator_died: 'anonymous (Detroit Publishing staff photographer)',
    created: 'between 1890 and 1901', first_published: { year: '1901 (catalogue)', venue: 'Detroit Publishing Co., Catalogue J (1901), no. 021344 — LoC: "Title and date from Detroit, Catalogue J (1901)"' },
    source_institution: 'Library of Congress, Prints & Photographs Division (Detroit Publishing Company Collection)', source_url: 'https://www.loc.gov/item/2016804446/', source_id: 'LC-DIG-det-4a15039 (call no. LC-D4-21344)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/det/4a10000/4a15000/4a15000/4a15039u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'Offered for sale in Detroit Publishing Co. catalogue (1901), before 1931.',
    pd_basis_worldwide: 'Anonymous corporate photograph made public by 1901: 70-year anonymous term expired.',
    clothing_check: 'PASS — no people in frame.',
    credit_line: 'Detroit Publishing Co. Library of Congress, Prints & Photographs Division, LC-DIG-det-4a15039',
    focal: { x: 0.45, y: 0.60 }, crop_hint: { x0: 0.02, y0: 0.04, x1: 0.98, y1: 0.97 },
    notes: 'Architecture-only frame: survives any wide crop (roof trusses y 0.05–0.35, apparatus y 0.5–0.75). LoC also lists a 166 MB "a" TIFF of the same negative; the 20.8 MB "u" TIFF was taken on this 8 GB shared machine (logged as a deviation).',
  },
  {
    file: 'ymca-gym.tif', tier: 'B', confidence: 'medium',
    title: 'YMCA gymnasium',
    subject: 'Gymnasium class: young men in singlets and shorts on parallel bars, a medicine ball and pulley weights; running track gallery above.',
    creator: 'National Photo Company (Herbert E. French, proprietor); photographer unrecorded', creator_died: 'anonymous (company staff); French died 1942',
    created: 'between 1910 and 1925 (LoC: "Date from negatives in same range")',
    first_published: { year: '1910–1925', venue: 'National Photo Company news and subject-set service to subscribers (LoC collection description)' },
    source_institution: 'Library of Congress, Prints & Photographs Division (National Photo Company Collection)', source_url: 'https://www.loc.gov/item/2016825295/', source_id: 'LC-DIG-npcc-31876 (call no. LC-F82- 845)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/npcc/31800/31876u.tif',
    rights_statement_verbatim: LOCN,
    pd_basis_us: 'Company photo service distributed to subscribers before 1931; LoC: no known restrictions on publication.',
    pd_basis_worldwide: 'Anonymous staff photograph (70-year anonymous term expired).',
    clothing_check: 'PASS — singlets, shorts, gym shoes.',
    credit_line: 'National Photo Company Collection, Library of Congress, Prints & Photographs Division, LC-DIG-npcc-31876',
    focal: { x: 0.44, y: 0.57 }, crop_hint: { x0: 0.02, y0: 0.36, x1: 0.97, y1: 0.97 },
    notes: 'CONDITION: a painted "YMCA" sign (a live registered mark) hangs at x≈0.41, y≈0.31. Any crop must stay below y≈0.36, or reject. Tier B for that reason only.',
  },
  {
    file: 'house-gym-dumbbells-1920.tif', tier: 'A', confidence: 'high',
    title: 'Girls in house gym',
    subject: 'Dumbbell drill on the lawn of the House Office Building: four women in blouses and skirts raising dumbbells overhead, instructor in sweater and shorts at left.',
    creator: 'National Photo Company; photographer unrecorded', creator_died: 'anonymous (company staff); French died 1942',
    created: '1920 May 4', first_published: { year: '1920', venue: 'National Photo Company caption list: "Dumb Bell exercises in the Court yard of the House Office Building…"' },
    source_institution: 'Library of Congress, Prints & Photographs Division (National Photo Company Collection)', source_url: 'https://www.loc.gov/item/2016827871/', source_id: 'LC-DIG-npcc-01517 (call no. LC-F8- 7735)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/npcc/01500/01517u.tif',
    rights_statement_verbatim: LOCN,
    pd_basis_us: 'News photo distributed 1920, before 1931; LoC: no known restrictions on publication.',
    pd_basis_worldwide: 'Anonymous staff photograph made public 1920 (70-year anonymous term expired 1990).',
    clothing_check: 'PASS — blouses, skirts, stockings; instructor in sweater, shorts, socks.',
    credit_line: 'National Photo Company Collection, Library of Congress, Prints & Photographs Division, LC-DIG-npcc-01517',
    focal: { x: 0.55, y: 0.50 }, crop_hint: { x0: 0.03, y0: 0.04, x1: 0.92, y1: 0.96 },
    notes: 'Landscape, a row of raised dumbbells across y≈0.35–0.5: made for a 3:1 crop. Emulsion flecks near the upper left.',
  },
  {
    file: 'tunney-pulleys-1926.tif', tier: 'B', confidence: 'medium',
    title: '[Gene Tunney, full-length portrait, standing, right profile, lifting weights on pulleys]',
    subject: 'Boxer Gene Tunney in singlet and shorts, right profile, pulling a weight-stack pulley machine; studio black ground.',
    creator: 'Pathé, Inc. (copyright claimant); photographer unrecorded', creator_died: 'anonymous (corporate)',
    created: 'c1926', first_published: { year: '1926', venue: 'Copyright 1926 June 21 by Pathé, Inc. (U.S. Copyright Office J284216)' },
    source_institution: 'Library of Congress, Prints & Photographs Division', source_url: 'https://www.loc.gov/item/89706448/', source_id: 'LC-DIG-ppmsca-19506 (BIOG FILE - Tunney, Gene)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/ppmsca/19500/19506u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'Published with notice 1926: US term 95 years, expired 1 Jan 2022.',
    pd_basis_worldwide: 'Anonymous corporate photograph published 1926 (70 years from publication = 1996).',
    clothing_check: 'PASS — singlet, shorts, canvas shoes.',
    credit_line: 'Pathé, Inc., 1926. Library of Congress, Prints & Photographs Division, LC-DIG-ppmsca-19506',
    focal: { x: 0.37, y: 0.30 }, crop_hint: { x0: 0.03, y0: 0.03, x1: 0.96, y1: 0.92 },
    notes: 'CONDITIONS: "©Pathé-Inc." is printed lower left (y≈0.94) — Pathé is a live company name, so crop above y≈0.92. Subject is a named celebrity who died 1978 (US post-mortem publicity rights can run 70 years in some states): decoration only, never named, never implying endorsement. The only machine-training image in the set.',
  },
  {
    file: 'jim-white-navy-1921.tif', tier: 'B', confidence: 'medium',
    title: 'Jim White, champion strong man of Navy, 10/6/21',
    subject: 'Strongman Jim White in a singlet and trunks, crouched, hauling a flag-draped motor truck by a rope in front of the House Office Building; onlookers.',
    creator: 'National Photo Company; photographer unrecorded', creator_died: 'anonymous (company staff); French died 1942',
    created: '[19]21 October 6', first_published: { year: '1921', venue: 'National Photo Company news service' },
    source_institution: 'Library of Congress, Prints & Photographs Division (National Photo Company Collection)', source_url: 'https://www.loc.gov/item/2016831474/', source_id: 'LC-DIG-npcc-05132 (call no. LC-F8- 16131)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/npcc/05100/05132u.tif',
    rights_statement_verbatim: LOCN,
    pd_basis_us: 'News photo distributed 1921, before 1931.',
    pd_basis_worldwide: 'Anonymous staff photograph made public 1921 (70-year anonymous term expired 1991).',
    clothing_check: 'PASS — singlet, trunks, boots.',
    credit_line: 'National Photo Company Collection, Library of Congress, Prints & Photographs Division, LC-DIG-npcc-05132',
    focal: { x: 0.30, y: 0.62 }, crop_hint: { x0: 0.07, y0: 0.08, x1: 0.95, y1: 0.93 },
    notes: 'Busy frame; the truck carries a banner (partly legible "…EASTERN…") from a 1921 veterans/unemployed march — crop to the lifter (x 0.2–0.6) to avoid a political banner. Heavy emulsion damage upper right.',
  },
  {
    file: 'strongman-acrobat-1923.tif', tier: 'A', confidence: 'medium',
    title: 'The strong man and the acrobat',
    subject: 'Stereograph: a strongman lying on his back balances an acrobat in costume on one raised foot; stage floor, black ground.',
    creator: 'Exhibit Supply Company (Chicago), publisher; photographer unrecorded', creator_died: 'anonymous (corporate)',
    created: '1923', first_published: { year: '1923', venue: 'Stereograph card No. 1, "Copyright 1923 by Exhibit Supply Company (Chicago, Ill.)" (U.S. Copyright Office J266222)' },
    source_institution: 'Library of Congress, Prints & Photographs Division (stereograph cards)', source_url: 'https://www.loc.gov/item/2024635608/', source_id: 'LC-DIG-stereo-1s51836 (LOT 11542-2)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/stereo/1s50000/1s51000/1s51800/1s51836u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'Published with notice 1923: US term expired 1 Jan 2019.',
    pd_basis_worldwide: 'Anonymous corporate photograph published 1923 (70-year anonymous term expired 1993).',
    clothing_check: 'PASS — tights, tunics and sashes (circus costume).',
    credit_line: 'Exhibit Supply Co., 1923. Library of Congress, Prints & Photographs Division, LC-DIG-stereo-1s51836',
    focal: { x: 0.27, y: 0.48 }, crop_hint: { x0: 0.03, y0: 0.04, x1: 0.50, y1: 0.90 },
    notes: 'Use ONE half of the stereo pair (left half shown in crop_hint). Copyright line printed bottom centre, number "1" lower left.',
  },
  {
    file: 'sikh-strongman-clubs-1907.tif', tier: 'B', confidence: 'medium',
    title: 'A Sikh strong man with his clubs, the heaviest 640 lbs., the smallest 160 lbs., India',
    subject: 'Stereograph: a bare-chested Indian strongman in a langot shoulders a huge wooden club among a ring of heavy carved clubs; turbaned crowd behind.',
    creator: 'H.C. White Co. (publisher); photographer unrecorded', creator_died: 'anonymous (corporate)',
    created: '1907', first_published: { year: '1907', venue: 'H.C. White Co. "Perfec" stereograph No. 14062, "Copyright 1907 by H. C. White Co."' },
    source_institution: 'Library of Congress, Prints & Photographs Division (stereograph cards)', source_url: 'https://www.loc.gov/item/2020681839/', source_id: 'LC-DIG-stereo-1s27102',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/stereo/1s20000/1s27000/1s27100/1s27102u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'Published with notice 1907, before 1931.',
    pd_basis_worldwide: 'Anonymous corporate photograph published 1907 (70-year anonymous term expired).',
    clothing_check: 'PASS — langot (fitted wrestler\'s brief), bare torso; crowd fully dressed.',
    credit_line: 'H.C. White Co., 1907. Library of Congress, Prints & Photographs Division, LC-DIG-stereo-1s27102',
    focal: { x: 0.30, y: 0.50 }, crop_hint: { x0: 0.09, y0: 0.07, x1: 0.49, y1: 0.87 },
    notes: 'The only photograph of heavy clubs (the ancestors of Indian clubs) in the set. Tier B: a named ethnic "strong man" as decoration needs Micah\'s judgement on tone; card mount text ("PERFEC STEREOGRAPH (Trade Mark)", H.C. White Co. — a defunct firm) must be cropped out. Use one half.',
  },
  {
    file: 'hine-gym-class-1910.tif', tier: 'B', confidence: 'medium',
    title: 'A gym. class, Henry St. Settlement, New York City. May 1910.',
    subject: 'Boys\' gymnasium class, hands on heads, seen from the gallery; pommel horse, onlookers along the railing.',
    creator: 'Lewis Wickes Hine, photographer', creator_died: '1940',
    created: '1910 May', first_published: { year: 'not established', venue: 'National Child Labor Committee files (Hine no. 1047); no publication before 1931 found for this frame' },
    source_institution: 'Library of Congress, Prints & Photographs Division (National Child Labor Committee Collection)', source_url: 'https://www.loc.gov/item/2018675326/', source_id: 'LC-DIG-nclc-04577 (print); also LC-DIG-nclc-05451 (glass negative)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/nclc/04500/04577u.tif',
    rights_statement_verbatim: 'No known restrictions on publication. For information see: "National Child Labor Committee (Lewis Hine photographs)," https://hdl.loc.gov/loc.pnp/res.097.hine',
    pd_basis_us: 'If published before 1931: expired. If unpublished: US term for unpublished works is life+70; Hine died 1940, so it ended 31 Dec 2010. PD either way; §14 test 1 is not proven for this frame.',
    pd_basis_worldwide: 'Hine died 1940: life+70 ended 2010.',
    clothing_check: 'PASS — shirts, ties, trousers.',
    credit_line: 'Lewis Wickes Hine, 1910. National Child Labor Committee Collection, Library of Congress, Prints & Photographs Division, LC-DIG-nclc-04577',
    focal: { x: 0.53, y: 0.62 }, crop_hint: { x0: 0.015, y0: 0.02, x1: 0.985, y1: 0.97 },
    notes: 'Tier B: publication before 1931 not established (US PD holds anyway). Subjects are children. The glass-negative scan (nclc.05451, 18 MB, cleaner) is the alternative; the rule said "largest", so the 54 MB print scan was taken.',
  },
  {
    file: 'western-hs-gym-1899.tif', tier: 'B', confidence: 'medium',
    title: '[Female students exercising in a gymnasium, Western High School, Washington, D.C.]',
    subject: 'Row of schoolgirls in gym dresses and bloomers, hands behind heads, lunging; wall bars behind. Cyanotype print photographed with a colour bar.',
    creator: 'Frances Benjamin Johnston, photographer', creator_died: '1952',
    created: '[1899?]', first_published: { year: 'not established', venue: 'Washington, D.C. school survey album (LOT 2749, no. 21); no publication before 1931 found for this frame' },
    source_institution: 'Library of Congress, Prints & Photographs Division (Frances Benjamin Johnston Collection)', source_url: 'https://www.loc.gov/item/2002695164/', source_id: 'LC-USZC4-9678 (colour transparency; cph.3g09678)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/cph/3g00000/3g09000/3g09600/3g09678u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'If unpublished: life+70, Johnston died 1952, ended 31 Dec 2022. PD either way; §14 test 1 not proven.',
    pd_basis_worldwide: 'Johnston died 1952: life+70 ended 2022.',
    clothing_check: 'PASS — long-sleeved gym dresses, bloomers, stockings.',
    credit_line: 'Frances Benjamin Johnston, c.1899. Library of Congress, Prints & Photographs Division, LC-USZC4-9678',
    focal: { x: 0.42, y: 0.46 }, crop_hint: { x0: 0.09, y0: 0.15, x1: 0.84, y1: 0.80 },
    notes: 'Tier B (publication not established). A cyan print: needs grayscale/duotone. Kodak colour bar and mount at right/top must be cropped. Subjects are minors. Bytes fetched from the Commons copy (tagged PD-old-70-1923, which asserts PD-US-expired + PD-old-70) because tile.loc.gov stalled; proven identical to the LoC master (download_url.byte_identity). The Commons tag is an assertion, not evidence of pre-1931 publication.',
  },
  {
    file: 'western-hs-dumbbells-1899.tif', tier: 'B', confidence: 'medium',
    title: '[Female students exercising with dumbbells, Western High School, Washington, D.C.]',
    subject: 'Schoolgirls in gym dresses doing a dumbbell drill in a hall; staircases either side.',
    creator: 'Frances Benjamin Johnston, photographer', creator_died: '1952',
    created: '[1899?]', first_published: { year: 'not established', venue: 'Washington, D.C. school survey album "Western High School" (LOT 2749 no. 026)' },
    source_institution: 'Library of Congress, Prints & Photographs Division (Frances Benjamin Johnston Collection)', source_url: 'https://www.loc.gov/item/2001699136/', source_id: 'LC-USZ62-5505 (cph.3a08812)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/cph/3a00000/3a08000/3a08800/3a08812u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'If unpublished: life+70 (Johnston d.1952) ended 2022. §14 test 1 not proven.',
    pd_basis_worldwide: 'Johnston died 1952: life+70 ended 2022.',
    clothing_check: 'PASS — gym dresses with belts, bloomers, stockings.',
    credit_line: 'Frances Benjamin Johnston, c.1899. Library of Congress, Prints & Photographs Division, LC-USZ62-5505',
    focal: { x: 0.45, y: 0.52 }, crop_hint: { x0: 0.0, y0: 0.0, x1: 1.0, y1: 0.93 },
    notes: 'Tier B. Low-resolution copy negative (1536 px wide). Handwritten "26" at bottom centre. Subjects are minors. Bytes fetched from the Commons copy (tagged PD-old-70-1923) because tile.loc.gov stalled; proven identical to the LoC master (download_url.byte_identity).',
  },
  {
    file: 'braddock-gym-1893.tif', tier: 'B', confidence: 'medium',
    title: '[Gymnasium, Braddock Carnegie Free Library, Braddock, Pennsylvania]',
    subject: 'Empty gymnasium under a steep timber roof with a tall arched window: rings, parallel bars, vaulting horse, medicine balls, racks of dumbbells (left) and Indian clubs (right).',
    creator: 'Photographer unrecorded (record names the architects Longfellow, Alden and Harlow)', creator_died: 'anonymous',
    created: '[1893]', first_published: { year: 'not established', venue: 'Photographic print in LOT 8908 (Carnegie libraries); no publication before 1931 found' },
    source_institution: 'Library of Congress, Prints & Photographs Division', source_url: 'https://www.loc.gov/item/2007684788/', source_id: 'LC-DIG-ppmsca-15372 (LOT 8908)',
    download_url: 'https://tile.loc.gov/storage-services/master/pnp/ppmsca/15300/15372u.tif',
    rights_statement_verbatim: NKR,
    pd_basis_us: 'If unpublished: anonymous unpublished works run 120 years from creation, 1893+120 = 2013, expired. §14 test 1 not proven.',
    pd_basis_worldwide: 'Anonymous: 70 years from creation if never made public (EU), expired.',
    clothing_check: 'PASS — no people in frame.',
    credit_line: 'Library of Congress, Prints & Photographs Division, LC-DIG-ppmsca-15372',
    focal: { x: 0.47, y: 0.47 }, crop_hint: { x0: 0.03, y0: 0.03, x1: 0.97, y1: 0.96 },
    notes: 'Tier B (publication). Visually the strongest empty-gym frame: the club racks and dumbbell racks read at hero size. Warm-toned albumen-look print.',
  },
  {
    file: 'saxon-trio-1911.tif', tier: 'A', confidence: 'high',
    title: 'Le Trio Saxon (Hermann, Kurt, Arthur) — Les rois de la force, p. 370',
    subject: 'The Saxon Trio — Hermann, Kurt and Arthur Saxon — standing shoulder to shoulder in wrestling singlets and laced sandals.',
    creator: 'Uncredited photograph reproduced in Desbonnet, Les rois de la force (1911)', creator_died: DESB.creator_died,
    created: 'before 1911', first_published: { year: '1911', venue: DESB.book + ', p. 370' },
    source_institution: DESB.source_institution, source_url: DESB.source_url, source_id: '4908148.0001.001.umich.edu, image 0388 (printed p. 370)',
    download_url: 'https://archive.org/download/4908148.0001.001.umich.edu/4908148.0001.001.umich.edu_tif.zip/4908148.0001.001.umich.edu_tif%2F4908148.0001.001.umich.edu_0388.tif',
    rights_statement_verbatim: DESB.rights_statement_verbatim, pd_basis_us: DESB.pd_basis_us, pd_basis_worldwide: DESB.pd_basis_worldwide,
    clothing_check: 'PASS — wrestling singlets (two-tone leotards), laced sandals.',
    credit_line: 'From E. Desbonnet, Les rois de la force (Paris, 1911), p. 370. University of Michigan Library scan via Internet Archive.',
    focal: { x: 0.60, y: 0.20 }, crop_hint: { x0: 0.235, y0: 0.08, x1: 0.97, y1: 0.78 },
    notes: 'Whole page is the original (1-bit bitonal 600 ppi scan: the halftone survives as dither, which suits Iron Age). Crop to the plate; faces sit at y≈0.13–0.16 of the page.',
  },
  {
    file: 'cyr-and-manager-1894.tif', tier: 'A', confidence: 'high',
    title: 'Louis Cyr et son manager, le 27 septembre 1894 — Les rois de la force, p. 459',
    subject: 'Louis Cyr in a spotted leotard top, embroidered trunks and tights, arms folded, beside his manager in a frock coat; parlour set.',
    creator: 'Uncredited photograph reproduced in Desbonnet (1911)', creator_died: DESB.creator_died,
    created: '27 September 1894 (caption)', first_published: { year: '1911 (this reproduction)', venue: DESB.book + ', p. 459' },
    source_institution: DESB.source_institution, source_url: DESB.source_url, source_id: '4908148.0001.001.umich.edu, image 0477 (printed p. 459)',
    download_url: 'https://archive.org/download/4908148.0001.001.umich.edu/4908148.0001.001.umich.edu_tif.zip/4908148.0001.001.umich.edu_tif%2F4908148.0001.001.umich.edu_0477.tif',
    rights_statement_verbatim: DESB.rights_statement_verbatim, pd_basis_us: DESB.pd_basis_us, pd_basis_worldwide: DESB.pd_basis_worldwide,
    clothing_check: 'PASS — leotard top, trunks, tights, shoes.',
    credit_line: 'From E. Desbonnet, Les rois de la force (Paris, 1911), p. 459. University of Michigan Library scan via Internet Archive.',
    focal: { x: 0.80, y: 0.33 }, crop_hint: { x0: 0.38, y0: 0.13, x1: 0.91, y1: 0.65 },
    notes: 'The only Louis Cyr image that passes: every Commons Cyr file failed (web-sourced, single tag, or a photo of a sculpture). Text wraps the left of the plate — crop to it.',
  },
  {
    file: 'athleta-1911.tif', tier: 'A', confidence: 'high',
    title: 'Athléta — Les rois de la force, p. 384',
    subject: 'Strongwoman Athléta (Athleta van Huffelen), full length, in a dark one-piece costume with a chevron belt and light ankle boots.',
    creator: 'Uncredited photograph reproduced in Desbonnet (1911)', creator_died: DESB.creator_died,
    created: 'before 1911', first_published: { year: '1911', venue: DESB.book + ', p. 384' },
    source_institution: DESB.source_institution, source_url: DESB.source_url, source_id: '4908148.0001.001.umich.edu, image 0402 (printed p. 384)',
    download_url: 'https://archive.org/download/4908148.0001.001.umich.edu/4908148.0001.001.umich.edu_tif.zip/4908148.0001.001.umich.edu_tif%2F4908148.0001.001.umich.edu_0402.tif',
    rights_statement_verbatim: DESB.rights_statement_verbatim, pd_basis_us: DESB.pd_basis_us, pd_basis_worldwide: DESB.pd_basis_worldwide,
    clothing_check: 'PASS — one-piece leotard costume, boots.',
    credit_line: 'From E. Desbonnet, Les rois de la force (Paris, 1911), p. 384. University of Michigan Library scan via Internet Archive.',
    focal: { x: 0.45, y: 0.18 }, crop_hint: { x0: 0.24, y0: 0.09, x1: 0.675, y1: 0.82 },
    notes: 'Tall narrow plate: wide crops land on face-and-shoulders only.',
  },
  {
    file: 'athleta-lille-1911.tif', tier: 'A', confidence: 'high',
    title: 'Athléta lorsqu\'elle enleva 175 livres à mon École de culture physique de Lille — Les rois de la force, p. 381',
    subject: 'Athléta, half-length profile, arms folded, in a sleeveless dark costume with a star pendant and medals.',
    creator: 'Uncredited photograph reproduced in Desbonnet (1911)', creator_died: DESB.creator_died,
    created: 'c. 1897 (text on p. 382 dates her Lille visit to 1897)', first_published: { year: '1911', venue: DESB.book + ', p. 381' },
    source_institution: DESB.source_institution, source_url: DESB.source_url, source_id: '4908148.0001.001.umich.edu, image 0399 (printed p. 381)',
    download_url: 'https://archive.org/download/4908148.0001.001.umich.edu/4908148.0001.001.umich.edu_tif.zip/4908148.0001.001.umich.edu_tif%2F4908148.0001.001.umich.edu_0399.tif',
    rights_statement_verbatim: DESB.rights_statement_verbatim, pd_basis_us: DESB.pd_basis_us, pd_basis_worldwide: DESB.pd_basis_worldwide,
    clothing_check: 'PASS — sleeveless costume top, medals.',
    credit_line: 'From E. Desbonnet, Les rois de la force (Paris, 1911), p. 381. University of Michigan Library scan via Internet Archive.',
    focal: { x: 0.49, y: 0.26 }, crop_hint: { x0: 0.155, y0: 0.07, x1: 0.91, y1: 0.79 },
    notes: 'Near-full-page plate with a strong profile: one of the best wide crops among the book plates (face and folded arms fit a 2:1 box).',
  },
  {
    file: 'apollon-portrait-1911.tif', tier: 'A', confidence: 'medium',
    title: 'Apollon, à l\'époque où il était dans toute sa beauté et toute sa force — Les rois de la force (plate facing p. 403)',
    subject: 'Strongman Apollon (Louis Uni), head and bare torso, studio portrait; plate ends above the waist.',
    creator: 'Uncredited photograph reproduced in Desbonnet (1911)', creator_died: DESB.creator_died,
    created: 'before 1911 (probably c.1890s, unsourced)', first_published: { year: '1911', venue: DESB.book + ', full-page plate after p. 402' },
    source_institution: DESB.source_institution, source_url: DESB.source_url, source_id: '4908148.0001.001.umich.edu, image 0421',
    download_url: 'https://archive.org/download/4908148.0001.001.umich.edu/4908148.0001.001.umich.edu_tif.zip/4908148.0001.001.umich.edu_tif%2F4908148.0001.001.umich.edu_0421.tif',
    rights_statement_verbatim: DESB.rights_statement_verbatim, pd_basis_us: DESB.pd_basis_us, pd_basis_worldwide: DESB.pd_basis_worldwide,
    clothing_check: 'PASS — bare torso only; the plate is cropped above the waist, nothing below is shown.',
    credit_line: 'From E. Desbonnet, Les rois de la force (Paris, 1911). University of Michigan Library scan via Internet Archive.',
    focal: { x: 0.58, y: 0.23 }, crop_hint: { x0: 0.20, y0: 0.045, x1: 0.94, y1: 0.855 },
    notes: 'The only Apollon photograph that passes (the Commons "Actor Uni Apollon" is a 1926 University of Washington print with a single US tag and doubtful identity). Face band y≈0.12–0.32 makes a clean wide crop.',
  },
];
